### ISSUE TITLE
Clearing world state is repeated 3 times

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#1128]
![1701121504](https://github.com/KittyCAD/modeling-app/assets/547923/c814d6eb-28a5-44b2-a570-76b3a57e1c9a)

Note the same entities being added each time.

**Comment by jessfraz** [comment]
i think these are related? https://github.com/KittyCAD/modeling-app/issues/868

**Comment by Irev-Dev** [comment]
Kinda not really, I don't think closing #868 would stop this from happening, but they are in the same area of code.

I'm making a guess, but it likely something along the lines of when things change, it's using the selections as the source of truth and sending through the selections again to the engine.

I have a few issues with this issue, like the title would probably be better as "redundant selection calls made to engine" because these are not world state clear calls. And not sure if "high priority" is called for? I mean does this have a bad UX associated with it?

**Comment by jessfraz** [comment]
just performance but yeah we can remove high priority but id like to get around to the perf bugs pre v1

**Comment by lf94** [comment]
Feel free to change the title, it's just what I did and observed

**Comment by lf94** [comment]
Yep! It's fixed now. I wonder how all of a sudden hahaha
