### ISSUE TITLE
Allow for the possibility of no `codeBasedSelections`?

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#1185]
As I'm implementing the Extrude command now that we'll have the command bar to allow for inputing a missing selection, I would like for it to be available either when:
1. Nothing is selected
2. One or more sketches is selected

I was able to use the `modelingMachine` [guard `'has valid extrude selection'` for the second](https://github.com/kittycad/modeling-app/blob/main/src/machines/modelingMachine.ts#L788), but I don't seem to be able to account for the first with the way things work today.

The issue is that you always have a cursor in the editor, and therefore a code-based selection. Even if you click in the background of the video stream the cursor jumps to the bottom of the editor, but it is still "selecting" the blank line.

I'll try out seeing if `codeBasedSelection` is on the last empty line for now as a proxy, but I don't know if that's the way you want to represent empty selections long-term.

**Comment by Irev-Dev** [comment]
You can't have no `codeBasedSelections` because you always need one cursor in the editor. Instead you need to query if the cursor position is relevant or not, so a cursor down on a blank line counts as no selection, and but I would also count any code that doesn't have a 3d representation to count as no selection, so a cursor somewhere in `// a comment` or `const simpleNumVar = 5` would be no selection too.

Is that okay?

Probably a few ways to do this, the easiest accounts for the fact that clicking in black space puts the cursor at the bottom of the page, we could just check `cursorPosition === code.length` or similar, this wouldn't capture comments etc though.
Otherwise we loop through the artifactMap and check if the cursor is within any of the artifact source ranges.

**Comment by franknoirot** [comment]
Ah okay that's fine, thank you I'll try that out!

**Comment by franknoirot** [comment]
Was able to take your recommended approach with https://github.com/KittyCAD/modeling-app/pull/1204, thanks
