### ISSUE TITLE
KCL: Inline comments for multiline expressions

### ISSUE THREAD

**Issue by greg-kcio** [KittyCAD/modeling-app#1528]
```
startSketchOn('XY')
  |> startProfileAt([0, 0], %)
  |> arc({
    radius: 1,  // currently
    angle_start: 0,  // these comments
    angle_end: 180  // are illegal
  }, %)
```

**Comment by Irev-Dev** [comment]
comments are trickier in kcl than they are in most languages.

We decided to put our comments as nodes in our AST, this has benefits to us, but also some drawbacks which is why it's not the norm.

Adding comments into your AST means you have extra nodes that have no meaning to the execution of you software. you also have to structure where your comments can go in your ast so that they can appear in different parts of your code.

```
const myVar = 5
// comment between two expressions
const myVar2 = 2
const myObj = {
  radius: 1, //this comment would need to be attached to the ObjectExpression
}
```

What are the benefits of putting comments in your AST?
It basically makes recasting while respecting existing comments.
If comments are not in your AST, then your recast will be striped of comments, and you will have to do a before-after comparison of oldCode, and newCode, to try and put the comments back in, which is non-trivial.

Having said all that we currently only support comments between expressions, which is why your examples are illegal. And my opinion is that fixing this is a pretty low priority. If someone is particularly passionate about this, ofc they are welcome to take a crack though ofc.

**Comment by jessfraz** [comment]
this is hard because those are serialized as json, like inline in the rest of the code should work right? maybe grackle fixes this cc @adamchalmers

**Comment by jessfraz** [comment]
for example inline comments outside a json body of a function should work: https://github.com/KittyCAD/modeling-app/blob/main/src/wasm-lib/kcl/src/ast/types.rs#L3037 we have tests for it, its merely because roight now those bodies to functions get serialized and derialized when they are objects like that, idk if grackle works like that, it might fix it if not

**Comment by jessfraz** [comment]
this is basically the same problem as the trailing comma, its just json bullshit

**Comment by jessfraz** [comment]
I tried on this one but advanced winnow-ing is hard

**Comment by Irev-Dev** [comment]
Ah yeah sorry Jess,
One thing I didn't make clear is that
```typescript
const myVar = 5
// comment between two expressions
const myVar2 = 2
```
and 
```typescript
const myVar = 5 // inline comment (but it's still between two expressions)
const myVar2 = 2
```
Are essentially the same, while one looks like an inline comment and the other not, they are still "comments between expressions" where one has a `/n` at the start and the other doesn't.

At least that's how it works from memory.

**Comment by Irev-Dev** [comment]
If the highest impact is being able to add comments between objectExpression properties, it won't be a general solution but we could update the typing for objectExpressions to allow non-code-meta between properties if that helps with snippets.

**Comment by adamchalmers** [comment]
I'm on it

**Comment by adamchalmers** [comment]
Arrays are done, working on objects.
