### ISSUE TITLE
Bug: Engine redrawing when there are no geometry edits

### ISSUE THREAD

**Issue by greg-kcio** [KittyCAD/modeling-app#1531]
The engine is re-modeling the scene on every change in-editor, including when I modify a comment or whitespace.

**Comment by Irev-Dev** [comment]
This should be resolved by grackle.
we are doing a very simple `JSON.stringify(oldAST) !== JSON.stringify(newAST)` atm to determine if we need to re-execute. because the ast contains source ranges and everything, even changes to white space or comments will cause a re-execute.
We could possible implement a proper compare function in rust to check only meaningful parts of the AST, but if we punt this it will just solves itself since the execution plan is the meaningful parts of the ast serialised anyway.

**Comment by greg-kcio** [comment]
That's good to hear! Closing since Grackle will resolve this.
