### ISSUE TITLE
Add new constraint symbols

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#1550]
This is a [figma](https://www.figma.com/file/5UUPOawPLEs3D0Gptf42vy/Designs?type=design&node-id=1260%3A3441&mode=design&t=83F46AJ6NA0G1ThW-1) grab

Design is not finalised so is likely to become stale.

The idea is we communicate how each segment is defined with symbols, and make them bolder or bright if the input is constrained (non-literal). We will also communicate how segments relate to each other with a little dot above the symbol, by highlighting the source-ranges and highlighting the related segments.

![image](https://github.com/KittyCAD/modeling-app/assets/29681384/53b03f18-c386-4a42-baca-ffc8ac58e353)

![image](https://github.com/KittyCAD/modeling-app/assets/29681384/7415b63d-98da-477c-b465-5116fe01674e)

**Comment by franknoirot** [comment]
@Irev-Dev I've mocked up what I think could be a few more requirements for this feature, and I've made a set of icons based on your diagram and added them to [our library in Figma](https://www.figma.com/file/5UUPOawPLEs3D0Gptf42vy/Designs?type=design&node-id=44-939&mode=design&t=xbvCpjFWFXyZArux-11)

![More constraint symbol rules](https://github.com/KittyCAD/modeling-app/assets/23481541/c7a25e12-cb78-4718-b24d-69aa53e37732)

1. Parameter icons appear near a segment’s head.
2. Their location is set in polar coordinates about the head’s point.
3. If they are “free”—still draggable and set to raw literals—they appear as the primary theme color.
4. If the parameter is constrained—defined by anything other than a literal—it cannot be dragged, and is shown in the text color.
5. If all parameters for a segment are constrained, the segment also gets “un-highlighted” by becoming the text color.
6. If a parameter references another part of the sketch or a constant, it is marked with a dot in addition to being text-colored.
7. The icons linger for 500ms after mousing off of the sketch. If the user hovers on an icon, a tooltip appears explaining it.

**Comment by franknoirot** [comment]
I think there's some value in having the colors go from highlighted (unconstrained) to inert/plain (constrained), because it's like the goal of creating a sketch is to have it be constrained and therefore predictable, even boring. I believe that is the metaphor tools like Onshape apply here. The only unconstrained thing in this sketch is the blue arc:

![Screenshot 2024-03-04 at 2 37 03 PM](https://github.com/KittyCAD/modeling-app/assets/23481541/66c6e180-ca0e-4ae0-bfb0-a335ed76aed2)

**Comment by franknoirot** [comment]
On great addition to my mockup that @Irev-Dev had when we met is to add a three-dot menu for more options to this list of constraints. In this menu popover we'll allow users to "release all constraints", change the function that they are using (such as lineTo instead of line), and more:

![Screenshot 2024-03-06 at 11 05 58 AM](https://github.com/KittyCAD/modeling-app/assets/23481541/11b8d8c3-c370-47c4-be00-9f4e74881e9d)

Also note that this line is still the primary color, because it has one constrained value but not all of them.

**Comment by franknoirot** [comment]
One additional consideration I just added to our notes in Figma (which I've [moved to a section of a new Sketch Mode page](https://www.figma.com/file/5UUPOawPLEs3D0Gptf42vy/Designs?type=design&node-id=1612-25383&mode=design&t=rhsyq2ppDHdWrjZd-11)). The corner used to position the icon container should change depending on where the segment is pointing in screen space:

![Screenshot 2024-03-06 at 11 53 57 AM](https://github.com/KittyCAD/modeling-app/assets/23481541/cf6cd327-c601-4e6a-90f5-5e81277a09cf)

**Comment by Irev-Dev** [comment]
Oh that alignment makes a tone of sense!
