### ISSUE TITLE
Cmd + K -> Extrude Crashes Modeling App

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#2190]
## Description
I pressed `cmd` + `k` then typed `extrude` and hit enter. My app crashed once I hit enter.

<img width="1912" alt="Screenshot 2024-04-22 at 12 12 29 PM" src="https://github.com/KittyCAD/modeling-app/assets/114548659/b03dacfe-cf3e-4fd1-8529-953f986d30c9">

## KCL
This was the KCL code I had right before I did it. I was trying to extrude the triangle sketch
```
const width = 12
const length = 12
const height = 12

const part001 = startSketchOn('XY')
  |> startProfileAt([-width / 2, -length / 2], %)
  |> lineTo([width / 2, -length / 2], %)
  |> lineTo([width / 2, length / 2], %)
  |> lineTo([-width / 2, length / 2], %)
  |> close(%)
  |> extrude(height, %)
const part002 = startSketchOn(part001, 'END')
  |> startProfileAt([2.95, 2.8], %)
  |> line([-4.38, -6.02], %)
  |> line([6.71, 0.13], %)
  |> close(%)
```

## Screen Recording

https://github.com/KittyCAD/modeling-app/assets/114548659/0cb517f9-4889-47c1-850c-4aad42e0bf31

**Comment by franknoirot** [comment]
Thanks, I think this has been around for a minute since our selection stuff changed but I'll see if I can fix it now

**Comment by franknoirot** [comment]
Okay I've found the source of the crashing and it is a very simple fix, but fixing it without fixing the selection behavior would mean that users would get even more confused, being unable to advance through the extrude command until they realized they need to click one of the lines of code in the sketch they want to extrude, which works, and not click the sketch profile they want to extrude, which doesn't. I'm investigating how to get that selection behavior to start working again.

This was missed because our E2E tests for Extrude only perform the "click a line of code" form of selection, not clicking in the 3D view, in an attempt to avoid flakiness. We need at least one test for that going forward. Luckily Kurt and Jess have been exploring ways of making those kinds of test less pixel-based and hopefully less flaky as a result.
