### ISSUE TITLE
[NEW FEATURE]: Switch between orthographic and perspective camera projection

### ISSUE THREAD

**Issue by r-barton** [KittyCAD/modeling-app#2210]
It would be helpful to visualize parts in an orthographic manner. For example if I wanted to visually check the clearance between 2 parts in a front on view, this is not possible with a perspective camera projection. Blender has a nice icon to toggle between views.

![image](https://github.com/KittyCAD/modeling-app/assets/3958831/16957286-b4b9-4c43-9166-b4b86b242c3e)

**Comment by franknoirot** [comment]
Here is [a mockup of a toggle](https://www.figma.com/design/5UUPOawPLEs3D0Gptf42vy/Designs?node-id=1612-21760&node-type=frame&t=GUZrRd4qqhSNJnxk-11) inspired by the Spline toggle:

![image](https://github.com/user-attachments/assets/76d626b8-54b3-492e-90a6-8c1596423065)

We currently have a way to toggle the perspective and ortho modes in the UI, just in a roundabout way. In @r-barton's words:

> First you need to have the debug panel on. Inside it you can turn off perspective cam

![image](https://github.com/user-attachments/assets/23838efe-bf9b-45e9-84f4-5a9b5683c5d4)

A new `PerspectiveOrthoToggle` component just needs created, wired up to the same logic as the checkbox in that debug panel, and it needs slotted into the `LowerRightControls` component (only when in the modeling view, look to see how the gizmo is removed on the home page).

One extra flourish is that it would be nice to persist the current toggle value so it stays between loads. You can add it to the [Store in ModelingMachine](https://github.com/KittyCAD/modeling-app/blob/main/src/machines/modelingMachine.ts#L160-L163), since it's very similar to openPanes.
