### ISSUE TITLE
[BUG]: Angle measurement direction when you dimension a line 

### ISSUE THREAD

**Issue by JBEmbedded** [KittyCAD/modeling-app#2304]
### Describe the bug

Angles are measured in the clockwise direction when you dimension a line (red curve). The typical convention is to go counterclockwise. Also it would be nice if sketch updated changes to dimensions like this when you make them. I am having to leave the sketch and come back to it in order for it to refresh and adjust the lines.
![angles](https://github.com/KittyCAD/modeling-app/assets/78819085/f75202fc-6203-494b-bb6e-80e3369cb2e8)

### Steps to Reproduce

N/A

### Expected Behavior

The typical convention is to go counterclockwise. Also it would be nice if sketch updated changes to dimensions like this when you make them. I am having to leave the sketch and come back to it in order for it to refresh and adjust the lines.

### Screenshots and Recordings

See above!

### Desktop OS

MacOS

### Version

v0.20.1

### Additional Context

N/A

**Comment by Irev-Dev** [comment]
https://github.com/KittyCAD/modeling-app/assets/29681384/5d4e5c58-bcc5-462a-a3fd-ce8b5a33a8a3

**Comment by nadr0** [comment]
> The typical convention is to go counterclockwise. 

The video above matches the expected workflow as well as matching Kurt's video back in May.
https://github.com/user-attachments/assets/152cbe7c-0331-459e-9d6b-7033410ac4a7

> Also it would be nice if sketch updated changes to dimensions like this when you make them. I am having to leave the sketch and come back to it in order for it to refresh and adjust the lines.

I was able to edit the variable of the angle constraint from the code editor and it updated the line properly. I did not have to go in and out of sketch mode to see any updates.

Additionally I was able to click and drag the line to update the constraint as well within sketch mode. 


I'll be closing this issue since this is working as expected and there is no bug reported. Please reopen this issue if there is any other findings.
