### ISSUE TITLE
"format code" isn't in the command palette.

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#2439]
To format your code, you can click a button in the GUI, or use a keyboard shortcut. But it doesn't exist in the command palette.

**Comment by franknoirot** [comment]
Since this is a command that will not need to be passed through any sort of state machine—it's really just an action that is always available in any context where the code editor is available—we should be able to accomplish it easily by doing the following:
1. Add a single-fire style `useEffect` to [KclProvider.tsx](https://github.com/KittyCAD/modeling-app/blob/main/src/lang/KclProvider.tsx#L51) which registers a command to the command palette in the same manner as other context-providing components like [SettingsAuthProvider.tsx](https://github.com/KittyCAD/modeling-app/blob/main/src/components/SettingsAuthProvider.tsx#L215)
2. Make this registered command fire the `kclManager.formatCode()` callback, just like the menu item in [KclEditorMenu.tsx](https://github.com/KittyCAD/modeling-app/blob/main/src/components/ModelingSidebar/ModelingPanes/KclEditorMenu.tsx#L41) does.
3. Export the "Code" icon from [our icon set in Figma](https://www.figma.com/design/5UUPOawPLEs3D0Gptf42vy/Designs?node-id=44-939&t=3jhmeixkl0glKs8b-11) as an SVG, register it as a [CustomIcon](https://github.com/KittyCAD/modeling-app/blob/main/src/components/CustomIcon.tsx) option, and use that as the command's icon

@jtran I'm going to assign this to you since I just gave you a big brain dump on how the command palette works (also I go back and forth on "command bar" vs "command palette", but I'm leaning toward the latter these days since it's becoming such a rich interface. would love your thoughts or renamings around the codebase if you have them)
