### ISSUE TITLE
Zoom Weirdness After Sketching on Face

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#2471]
## Description
Couple things:
- clicking on a face to sketch on orients the camera far away from the model.
- while zooming into the model, the model disappears. It will reappear once I stop zooming

## Version
v0.21.7

## Recording
https://github.com/KittyCAD/modeling-app/assets/114548659/8f475f40-e538-4b89-86df-ccf202fb1cc2

**Comment by jgomez720** [comment]
@jessfraz delegate as needed

**Comment by jessfraz** [comment]
are these the same bug https://github.com/KittyCAD/modeling-app/issues/2209

**Comment by jgomez720** [comment]
No not quite. This one is only after selecting "start sketch" and selecting a face. Once it orients the camera to the face, then the weirdness happens that's in the video. The model will disappear as you zoom in or out, and when it first orients, it orients the camera far away from the model

**Comment by franknoirot** [comment]
> The model will disappear as you zoom in or out

This part is expected behavior (see [`shouldHideScene`](https://github.com/KittyCAD/modeling-app/blob/main/src/clientSideScene/ClientSideSceneComp.tsx#L48-L69)). Since the engine scale would lag behind the sketch scale update when you zoom it is instead hidden. That's definitely a debatable UX compromise though.

**Comment by Irev-Dev** [comment]
I'm almost certain this has been fixed (can't replicate), reopen if I'm wrong.
