### ISSUE TITLE
Write tauri tests for file tree

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#2529]
**Edit**: problems from the original description have been resolved, Issue left open for writing tauri tests to cover these cases.

---

- delete no longer works
- rename does not work
- when you create a file it should not make a file, hitting escape in the form should cause zero changes to file system

https://github.com/KittyCAD/modeling-app/assets/1445228/9c1cba32-d21b-40c2-b847-f0b03056c0b9

I think before we touch this code again we need e2e tests otherwise we will constantly be rewriting the same code

I'll help on the e2e side

**Comment by Irev-Dev** [comment]
Zoom to fit can definitely be weird, I'm not sure if it's the same as what your seeing but I raised a problem with a specific kcl example, I figure the more we can point out specific examples of it not working, that at lest gives really solid replication steps for the engine crew

https://github.com/KittyCAD/engine/issues/2310

Either way not part of this issue.

I'm going to rename this since it's only being left open as a reminder to write tauri tests.

**Comment by franknoirot** [comment]
The third item in this list:
> when you create a file it should not make a file, hitting escape in the form should cause zero changes to file system

Is a great idea, but requires changing how file creation business logic works. I would like to spin it out into its own issue, and consider this issue closed when #3569 merges, for the purposes of this Electron migration.

**Comment by jessfraz** [comment]
no worries its in a nother issue let me find https://github.com/KittyCAD/modeling-app/issues/3248 so def dont owrry

**Comment by franknoirot** [comment]
Ah damn I should've check that there was an issue already let me past in the contents from https://github.com/KittyCAD/modeling-app/issues/3605 over to your issue and close as duplicate.
