### ISSUE TITLE
when your kcl has an error the error message diagnostic is getting cleared right after

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#2755]
i think this is part of the lsp and ts raccing sorry @paultag 

easy to repro locally, just have an error in your kcl and it will go away right after, it needs to be an execution error like something from the engine theres an example in playright

playright is likely passing because it does show forr a second but then it disappears

**Comment by jessfraz** [comment]
okay now im hit or miss on reproducing this

**Comment by Irev-Dev** [comment]
playwright could be changed to 
```typescript
await expect(//diognostic to be there
await page.waitForTimeout(1000)
await expect(//diognostic to still be there
```
To avoid this kinda race condition from stricking again once fixed?

**Comment by paultag** [comment]
I'm having a hard time duping this (also tried using playwright sleeps which i want to add to ensure we don't regress once I understand the race) -- but obviously I believe there's an issue here, going to look through likely suspects and see if I can rationalize where this is coming from; I'll do another pass or two through the linter code specifically since that's where it prob is.

I'm hopeful that a larger refactor will get us out of this mess; sharing state is likely the way out even without knowing the specifics yet

**Comment by paultag** [comment]
Is there any possibility there was a lint in addition to an error on your KCL @jessfraz ? I can get it to fight but only if I set a lint error in addition to an error -- is the same or a different bug?

**Comment by jessfraz** [comment]
yes 100% i bet thats it
