### ISSUE TITLE
Selection order should not matter for constraints

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#2776]
Here's a video of how to replicate the bug for the equal-length constraint, but it, likely applies to a few other's, so part of the issue is checking the other constraints.

https://github.com/KittyCAD/modeling-app/assets/29681384/c8e71d92-7c74-4151-a014-8dc08ba25a00

Tasks:
- [x] Fix for equal length constraint
- [x] Check which other constraints are affected and fix them
- [x] Make sure there are tests, a unit test might suffice since it's likely an AST mod bug.

Pointers:
equal length code is pretty much all in `src/components/Toolbar/EqualLength.tsx` so that's where I would start. It might be as simple as reordering [`selectionRanges.codeBasedSelections`](https://github.com/KittyCAD/modeling-app/blob/f4877cb16099cb773adcc7b6eb3c4b24d567a4c8/src/components/Toolbar/EqualLength.tsx#L28) by source ranges, but I'm not sure.

**Comment by jtran** [comment]
I'm having trouble reproducing this in my development environment. I started by pasting the same initial kcl into the editor, and then I edited the sketch visually in the same way. But the resulting kcl looks like this, which is what we expect.

```kcl
const sketch001 = startSketchOn('XZ')
  |> startProfileAt([0.76, 0.58], %)
  |> line([0.35, 0.83], %, $seg02)
  |> angledLine([35, segLen(seg02, %)], %)
  |> line([2.12, 0.11], %, $seg01)
  |> angledLine([-65, segLen(seg01, %)], %)
```

Was there some other action done that was cut from the video that might have led to an invalid state?

**Comment by jtran** [comment]
We determined that the problem only arises in Chromium-based browsers. Safari, Tauri app on macOS, and Firefox all work as expected.

**Comment by Irev-Dev** [comment]
> Make sure there are tests, a unit test might suffice since it's likely an AST mod bug.

We might chat about the best way to test this after we figure out what the bug actually is, because my initial hunch of AST mod bug seems less likely with the "not on webkit" revelation.

**Comment by jtran** [comment]
After investigating it some, I realized that I could only reproduce the problem when DevTools was _closed_. So this is likely a race condition and _not_ browser-specific.

**Comment by franknoirot** [comment]
I'm a little confused, sorry I must have missed this discussion, but I don't understand why this isn't trivially replicable in any browser or on desktop.

Happy path:
1. Draw any path, say with 4 segments
2. Select the second segment
3. Hold <kbd>Shift</kbd> and select the third segment
4. Apply any relevant constraint, say the "Equal length"constraint
5. Works as expected

Unhappy path:
1. Draw any path, say with 4 segments
2. Select the second segment
3. Hold <kbd>Shift</kbd> and select the third segment
4. Apply any relevant constraint, say the "Equal length" constraint
5. Sketch breaks, because it now has invalid code

Before applying a constraint code mod, we should sort the selection in dependency order.
