### ISSUE TITLE
Creo mouse controls are displayed incorrectly

### ISSUE THREAD

**Issue by ZooSpiritWolf** [KittyCAD/modeling-app#2804]
🐛 on Dev

Steps to reproduce:
1. Login
2. (Optional) - Change the default mouse controls to "Creo" in the onboarding flow
3. Click top-right hamburger menu
4. Click "Settings"
5. Click "User" tab
6. Scroll down to "Mouse Controls"
7. Change the default mouse controls to "Creo" if not changed in onboarding flow
8. Observe Creo controls
Expected: Creo controls to be correctly displayed
Actual: Creo controls are displayed incorrectly and displays the "NX" controls

Timestamp: 0:12
Video: 
https://www.loom.com/share/9327d9dfb2954cf7936e459af345855d?sid=2faa5409-e1ce-45fe-9c60-5cc02a728973 (https://www.loom.com/share/9327d9dfb2954cf7936e459af345855d?sid=2faa5409-e1ce-45fe-9c60-5cc02a728973)

Bug report:
https://app.qawolf.com/zoo/bug-reports/9cbecaff-5a35-4499-968b-3c5c44fa9b3b

Affected workflows:
• Bug: Creo mouse controls are incorrect - https://app.qawolf.com/zoo/workflows/clxuvnkm6025q12qs18yvxdbk

If you are aware of this bug you can set the priority to low which will prevent it from causing a run failure.

**Comment by franknoirot** [comment]
@jtran I don't think this issue should be too crazy and should take you on a brief tour of some of the settings system and camera system, so I'm gonna assign over to you but ofc hit me up with any questions. Here's some context:
- Creo's controls, at least according to my read of [their docs](https://support.ptc.com/help/creo/ced_3daccess/r20.6.0.0/en/index.html#page/ced_3daccess/zoom_and_rotate.html), appear to be:
  - Zoom: Ctrl+right mouse and drag
  - Pan: Ctrl+left mouse and drag
  - Revolve: Ctrl+middle (or left+right) mouse and drag 
- Our Creo camera controls definition lives [here in cameraControls.ts](https://github.com/KittyCAD/modeling-app/blob/main/src/lib/cameraControls.ts#L157-L171)
  - (feel free to [rename `butName`](https://kittycadworkspace.slack.com/archives/C04KFV6NKL0/p1720030476359919?thread_ts=1720016166.948659&cid=C04KFV6NKL0) while you're in there 😁)
  - I suspect that trying to get the `left+right mouse and drag` could be quite tricky to get working since none of the other control sets have done that, so I leave that as an optional extension. I think regardless it would be good to try to trace it through to where the mouse event listeners actually get created and used.
