### ISSUE TITLE
workflow bug w rectagle + delete

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#2844]
1. start sketch
2. draw rectange
3. delete rectangle code
4. chose line tool
5. cant draw line

**Comment by franknoirot** [comment]
When you say "delete rectangle code", do you mean you leave the `startProfileAt` or delete that too? If you delete it too the line tool works for me, if you leave it it doesn't, because the first click of the line tool assumes that it needs to start the profile.

https://github.com/KittyCAD/modeling-app/assets/23481541/10b139e7-e963-4221-b538-0117b65ed37a

A quick fix is to make that addition of `startProfileAt` conditional in the line tool's first click, but this is one of the things that is making me feel we need a new way of working with the code mods in sketch and elsewhere.
