### ISSUE TITLE
Command Bar - Updating a setting's value then clicking the "Level" argument unintentionally saves the setting

### ISSUE THREAD

**Issue by ZooSpiritWolf** [KittyCAD/modeling-app#2882]
🐛

Steps to reproduce:
1. Login
2. Click the "Command Bar" button
3. Select a setting with multiple value options listed
4. Type one of valid "Value" options up to the point where it is the only remaining option
5. Click the "Level" argument button
Expected: To navigate back to the "Level" argument tab
Actual: Setting is submitted and saved as the selected option although the setting was not intended to be submitted or selected

Timestamp: 0:05
Video: 
https://www.loom.com/share/f68414f34f2d4e90952331ae066f9993?sid=30cd9ec5-810d-45ec-a605-8c31c5d206db (https://www.loom.com/share/f68414f34f2d4e90952331ae066f9993?sid=30cd9ec5-810d-45ec-a605-8c31c5d206db)

Bug report:
https://app.qawolf.com/zoo/bug-reports/916d85a6-cb92-4345-bd5c-8548edebfdce

Affected workflows:

If you are aware of this bug you can set the priority to low which will prevent it from causing a run failure.

**Comment by franknoirot** [comment]
Is this still occurring? I am not experiencing it on app.zoo.dev at the moment


https://github.com/KittyCAD/modeling-app/assets/23481541/6b97484d-15c3-4475-b125-00f38413bbac

**Comment by Irev-Dev** [comment]
Frank got some clarification on this one
![image](https://github.com/KittyCAD/modeling-app/assets/29681384/3642ce65-0647-4b5a-9fa3-bcbe826dfd20)

https://www.loom.com/share/cf2c96f21ba245ffbb3cc12f99c172c2

Looks like it can still be replicated.

**Comment by franknoirot** [comment]
Okay I figured out what's causing this and have written up a failing test for it, but I have to figure out how to stop it now.

Basically we call onSubmit whenever a new option is selected in the command bar's option input ([here](https://github.com/KittyCAD/modeling-app/blob/main/src/components/CommandBar/CommandArgOptionInput.tsx#L86)), and for some reason clicking away to another argument can sometimes trigger that (I suspect because internally in that combobox component it changes the selected option if the input is blurred and there is only one option available from the list).

We don't want that submission step to happen in certain cases, but do in most. But that combobox component only gives us access to the new selected option's value, not the underlying event that triggered the change, which is how I would like to discriminate on whether we should submit or not.

**Comment by franknoirot** [comment]
Yeah [right here in the headless UI docs](https://headlessui.com/v1/react/combobox#keyboard-interaction):
> `Tab` when combobox is open | Selects the current active item and closes the combobox

Damn it really is like this combobox is just incompatible with how we really want to use it. I guess I thought I could get away without defining every possible behavior, but it feels like I really have to.
