### ISSUE TITLE
Add tools back into cmdBar

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#2924]
https://github.com/KittyCAD/modeling-app/pull/2917/files#r1666203776 removed tools out of the cmd bar because the config expects individual events, not events with data (needs to be `{type: 'change tool', data: 'line'}` etc.

**Comment by franknoirot** [comment]
The tricky bit with this is that currently `useStateMachineCommands`, and more deeply the `CommandSetConfig` type, assume that there is one command per state machine event. What needs to be done is allow for there to be multiple commands per event, or divorce them in some way such that one state machine event maps to multiple commands each with different built-in, static payloads.

Maybe the mapping for command configurations should be inverted from how it is today. Instead of mapping _from_ state machine events _to_ command configs, we should allow command authors to create any set of configs they want, and just require that they specify what event they're gonna invoke and what (if any) payload will be included along with it.

**Comment by franknoirot** [comment]
Okay it seems that the other incorrect assumption that _any command bar commands_ make (not just those tied to a state machine) is that every part of the defined payload is an argument that the user should be shown an input for. This use case calls for:
1. One state machine event (`"change tool"`) to be associated with multiple command bar commands
2. Each of those commands have a payload (`{ tool: SketchTool }`) that the user has no input on, and thus they should be treated as if there are no arguments in the command bar
