### ISSUE TITLE
Debug mode that displays the scene at every intermediate step

### ISSUE THREAD

**Issue by jtran** [KittyCAD/modeling-app#2932]
We're in a unique position to improve the development experience. When writing code, whether it's KCL or any other language, the developer has to read the code, simulate the execution, and imagine the output at every intermediate step. Because KCL has output that can be visualized, it's great that we always, immediately display it. But it would be nice if we had a debug mode where we also displayed the output at every intermediate step to help developers find where their program went wrong.

For a visual example of what I mean, see Bret Victor's [Substroke](https://worrydream.com/substroke/). In that, when you create a drawing, you add transform operations step-by-step, the output of each step is displayed horizontally, and the final result is the right-most image. The developer can see the steps that brought them to the final result without having to simulate the computer's execution. To paraphrase Bret Victor and Jonathan Edwards before him, the computer is already doing this execution. Why can't it just display it?

For another example, see the Nile programming language, around [this timestamp](https://youtu.be/ubaX1Smg6pY?t=3317) in Alan Kay's talk.

**Comment by Irev-Dev** [comment]
Because the FE doesn't get the intermediate steps, do we think this would require engine side changes too?

Or might we get some of this stuff for free just by having a step through debugger, as we step through is LOC it will fire off more modelingCommands building up the model slowly, and so long as we keep track of things possible we could tell the engine to delete features if the user wants to travel backwards through time? (that might not be simple, I don't think we have delete endpoints of every time of entity, like fillets etc)

**Comment by jtran** [comment]
I'll close this for now, but I'm not giving up on it.
