### ISSUE TITLE
"User Menu" onboarding modal has incorrect description

### ISSUE THREAD

**Issue by ZooSpiritWolf** [KittyCAD/modeling-app#2939]
🐛

Steps to reproduce:
1. Sign up for a new account
2. Close the "Modeling app" banner
3. In the "Welcome to Modeling App!" modal, click the next button until the user is brought to the "User Menu" modal
Expected: Description states "Click the hamburger menu in the upper right corner to open the user menu. You can change your settings, sign out, report a bug, or request a feature."
Actual: "Click your avatar" (not visible, hamburger menu is in its place), and "report a bug" is not listed in the things the user can do in the user menu although it is an option visible in the user menu.

Video: 
https://www.loom.com/share/156adcd54ec24d9494da344d107295ed?sid=a2a04a3c-8140-4653-b314-8c4178841a61 (https://www.loom.com/share/156adcd54ec24d9494da344d107295ed?sid=a2a04a3c-8140-4653-b314-8c4178841a61)

Bug report:
https://app.qawolf.com/zoo/bug-reports/8fe72575-9bb4-44a4-938c-23610826ef6b

Affected workflows:

If you are aware of this bug you can set the priority to low which will prevent it from causing a run failure.

**Comment by jessfraz** [comment]
our test for this must not be working anymore cc @franknoirot

**Comment by franknoirot** [comment]
Yeah you know what I bet our test for this didn't cover the case if the user had **no avatar image** on their profile, only if the avatar image URL 404'd.

@lf94 I think this'll be dead easy for you to switch since you helped me with that test before. Here's some context refresher in case it helps:
1. The test is ["Avatar text updates depending on image load success"](https://github.com/KittyCAD/modeling-app/blob/main/e2e/playwright/flow-tests.spec.ts#L2352-L2415) in flow tests. I think this test is missing a case where the user object has an undefined image instead of a 404ing one, and I hypothesize it will fail if we add one
2. The [UserMenu.tsx](https://github.com/KittyCAD/modeling-app/blob/main/src/routes/Onboarding/UserMenu.tsx#L13-L27) step in onboarding doesn't currently have a way to know that no image loading was attempted if the user's avatar is nonexistent. Maybe we should fire that error over in [UserSidebarMenu](https://github.com/KittyCAD/modeling-app/blob/main/src/components/UserSidebarMenu.tsx#L46-L64), and allow it to try and load even if `!user.image`?

**Comment by lf94** [comment]
https://github.com/KittyCAD/modeling-app/pull/2959 should close it

**Comment by jessfraz** [comment]
this is still failing in qawolf

**Comment by jessfraz** [comment]
"the "report a bug" feature is still not mentioned in the user menu modal, which caused the test to fail on our end"

**Comment by franknoirot** [comment]
> "the "report a bug" feature is still not mentioned in the user menu modal, which caused the test to fail on our end"

Oh okay easy fix, should take me just a moment.
