### ISSUE TITLE
Planes Missing From "Select Plane to Sketch On"

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#3041]
### Description
When I click on **Start Sketch**, the planes are not showing up for me. Unfortunately, I'm not sure how to reliably reproduce it, but I did see it.

### Version
v0.24.1

### Recording
https://github.com/user-attachments/assets/eb445d00-cd42-466c-ac67-5804f6a5d9fa

Not sure who to assign, so please reassign as needed

**Comment by Irev-Dev** [comment]
I'm going to close this with #3047

Though I'm only 95% sure I was able to replicate the same bug. For example I was able to replicate the default planes not showing up, but it was very temporary. if I exited the broken plane selection and then hit "start sketch", it would come good without needing a refresh, which from the video at least I couldn't tell if that was the case for you.

When you hit bugs that are hard to replicate, I appreciate you taking a video of it working while the bug is present, but a core dump and probably a screen shot of the console would also be useful.
