### ISSUE TITLE
Codemirror diagnostics are not selectable

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#3057]
Codemirror diagnostics are not selectable, can't copy paste, maybe we should even have a copy-to-clipboard icon on them

https://github.com/user-attachments/assets/00a0e5b6-7023-4ba7-889d-a25fbce81599

Here's some sample code that will give you an error to reproduce

```js
startSketchOn('XY')
  |> startProfileAt([10, 0], %)
  |> arc({
       angle_start: 180,
       angle_end: 180,
       radius: 1.5
     }, %)
  |> close(%)
  |> patternCircular2d({
       arcDegrees: 360,
       center: [0, 0],
       repetitions: 5,
       rotateDuplicates: true
     }, %)
```

**Comment by jessfraz** [comment]
It’s a div w text so it should be… z-index issue?

**Comment by jessfraz** [comment]
My money is it’s a css thing

**Comment by jessfraz** [comment]
We can custom style these little shits

**Comment by jackdelamotte** [comment]
Was interested in testing out the dev env and tackling a good starter issue so I looked into this! Was able to make the tooltips selectable with the following code in `hover.ts`:

```
import { Extension } from '@codemirror/state'
import {
  hoverTooltip,
  tooltips,
  ViewPlugin,
  EditorView,
} from '@codemirror/view'

import { LanguageServerPlugin } from './lsp'
import { offsetToPos } from './util'

export default function lspHoverExt(
  plugin: ViewPlugin<LanguageServerPlugin>
): Extension {
  return [
    hoverTooltip((view, pos) => {
      const value = view.plugin(plugin)
      return (
        value?.requestHoverTooltip(view, offsetToPos(view.state.doc, pos)) ??
        null
      )
    }),
    tooltips({
      position: 'absolute',
      parent: document.body,
    }),
    EditorView.baseTheme({
      '.cm-tooltip': {
        fontSize: '12px',
        maxWidth: '400px',
      },
    }),
  ]
}
```

Just set `parent: document.body` and added some custom styling, which could be tweaked or moved somewhere common. Also tried figuring out how to add a copy to clipboard button but wasn't having a lot of luck. Definitely seems like there's a way to do it though. Happy to open a proper PR if I can get added as a contributor, otherwise just figured this could add to the discussion. Cool stuff y'all!

**Comment by jessfraz** [comment]
wow thanks!

**Comment by jessfraz** [comment]
You can open a PR from a fork! thanks so much!

**Comment by jackdelamotte** [comment]
Cool! Opened!
