### ISSUE TITLE
Add an `int()` stdlib function to KCL

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#3081]
We currently have no way in KCL to go from a floating point to an integer type, but it should be pretty trivial to create a standard library function to coerce a passed in number.

**Comment by lf94** [comment]
For more context this is useful for functions which require an integer parameter

**Comment by jtran** [comment]
What happens if the floating point number is `-1.5`? There are many options for what to do, including error out because it's not representable as an integer. In Rust, for example, you first have to make sure it doesn't have a fractional part by calling [one of these](https://doc.rust-lang.org/std/primitive.f64.html#method.floor). My impression is that KCL is a little more fast and loose. But please at least consider the consequences first 🙇

**Comment by lf94** [comment]
-1 is a valid integer though? And functions which can't take negatives would error?

**Comment by jtran** [comment]
Yes, there are many ways to round. There isn't a right answer, which is why all languages expose many ways to do it.

**Comment by franknoirot** [comment]
Yeah I have no preference on how we go about it. I'd be perfectly happy with using [`floor`](https://zoo.dev/docs/kcl/floor) or [`ceil`](https://zoo.dev/docs/kcl/ceil) functions exclusively and foregoing an `int` function entirely (and closing this issue) if I could pass the output of all of those functions into a function that requires an integer parameter like [`patternTransform`](https://zoo.dev/docs/kcl/patternTransform) does for its iteration counts.

**Comment by jtran** [comment]
I originally missed the [Slack thread](https://kittycadworkspace.slack.com/archives/C06P9L5MCUD/p1721415881989909?thread_ts=1721415188.053659&cid=C06P9L5MCUD) about this. I think the consensus was that `floor`, `ceil`, and family are `float -> float`. Only this new function is `float -> int`, i.e. returns an integer.
