### ISSUE TITLE
Camera snaps back when rapid-fire dragging

### ISSUE THREAD

**Issue by mlfarrell** [KittyCAD/modeling-app#3125]
see video

https://github.com/user-attachments/assets/6e33d3f0-a094-4453-945f-f8e1c41bab94

**Comment by franknoirot** [comment]
Is this a KCL sample we have made @mlfarrell, or do you otherwise have this KCL to try and reproduce using your exact setup? I am no longer able to reproduce, my apologies for not attempting to reproduce this right away.

We have made some simplifications to our stream lately (#3691, #3825 and #3867 are coming to mind), and are no longer tracking state that may have been the root cause of this. It seems apparent to me that a queue of camera commands was building up and then stale ones were coming in and clobbering new ones.

**Comment by mlfarrell** [comment]
i'll try to reprod it next week.  you can close this as a dupe of the other issue and link to this from there if you want to cut down on issue noise
