### ISSUE TITLE
KCL error diagnostics are not redrawn when pane is reopened

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#3209]
If you have KCL errors in your code and you close the code pane, the error diagnostics are not repainted when you open the panel again. You have to edit the code by adding or deleting a character for everything to redraw.

Steps to reproduce:
1. Have valid KCL in the code pane
2. Break it some how, see the diagnostics
3. Close and reopen the pane
4. You should see no diagnostics

**Comment by franknoirot** [comment]
This might be a good one for @jessfraz or @paultag since they've touched editor stuff most recently.

**Comment by jessfraz** [comment]
We need to re-execute on code pane open, since the component was unloaded

**Comment by jessfraz** [comment]
but we dont want to re-execute always in that component, _only_ on code pane open

**Comment by Irev-Dev** [comment]
> We need to re-execute on code pane open, since the component was unloaded

I think this implies that we need to keep the state somewhere other than only in the codeMirror component so that we can re-apply it to codemirror when the pan re-opens. Either that or we change how the codemirror pane is closed such that it's hidden not unmounted (I feel like we've had other bugs from unmounting codemirror.

I know you've already got a fix so this might be too little too late, but something to keep in mind.

**Comment by jessfraz** [comment]
yeah i ended up doing it right :) no execution necessary
