### ISSUE TITLE
Electron test: (regression) right/left arrow in input causes weird behavior

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#3259]
we will want playwright tests / tauri tests / etc for this 

https://github.com/user-attachments/assets/4a96d11e-b30a-4251-8cc4-4f21befadf3a

**Comment by Irev-Dev** [comment]
I have a quick go at this, without much luck here's a sample of the kind of things I was trying

<img width="661" alt="image" src="https://github.com/user-attachments/assets/8f2761ec-7def-43da-a341-3fbaed5329e8">

And basically it's all very heavy handed and doesn't solve the root problem which is why is this happening in the first place.

I can detect when the arrow keys are being press and simply `preventDefault` will stop the characters being added, but it also nukes everything else like the cursor moving, and going down the path of moving the cursor ourselves seems like a very bad idea. I tried a couple things but ultimately this is just a normal text input, I don't know why it's being weird.

I half wonder if electron will fix this lol.

**Comment by franknoirot** [comment]
You know what's fun is I can't reproduce this if I open dev tools before trying it

**Comment by Irev-Dev** [comment]
I asked Pierre or Lee to see if they can reproduce in electron, I think atleast 10% chance this is some safari bullshit.

**Comment by lf94** [comment]
Works fine here :)

**Comment by jessfraz** [comment]
Okay cool let’s close w the electron stuff we can add a test

**Comment by Irev-Dev** [comment]
Is there an electron issue we can link this to?

we're not in stealth mode with electron anymore haha, so maybe we should have an issue for it.

**Comment by Irev-Dev** [comment]
Done in https://github.com/KittyCAD/modeling-app/pull/3315/commits/cc9aedd1ac8e80a64c180ff3d99ffd6c1deb1d52, can close out when we merge the electron branch
