### ISSUE TITLE
Electron tests: model export

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#3376]
Exporting a model should save it to the disk.

1. Create a new project
2. Click on the project
3. Add KCL
4. Click on "Export current part"
5. Select gltf as the type
6. Save
7. Check the file size matches exactly what we expect.

**Comment by Irev-Dev** [comment]
We have export tests for the web app where after we do the export we send the file to the CLI for a screen shot, I think we should do the same here instead of matching the file size, as it's both a better saniy check and should be less brittle.

If David changes something in the header than the file size is going to change.
