### ISSUE TITLE
Electron test: (regression) loading a large file from file pane

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#3470]
1. open a project with multiple files (one of the files takes a long time to load, just use like a lego thats 9x18)
2. load a normal file
4. open the large file FROM THE FILE PANE
5. while its "executing" to try open another
6. then you cannot load any after

then test

1. open large file from projects
2. then try to execute and load other files stopping that one mid execute

so basically test that you can still open fies even if you cancel opening a large one from the file pane (this has to be from the file pane)

**Comment by nadr0** [comment]
I am testing this workflow locally. I have a small cup shape in `cup.kcl` and a 9x18 lego in `big-lego.kcl`. 

- load into my project
- loads into `cup.kcl`
- click `big-lego.kcl` in the Project Files pane
- Starts to render the big lego, takes 5 ever
- Click `cup.kcl` in the Project Files pane
- Loads the KCL Code (codemirror) but rendering is still trying to render the `big-lego.kcl`
- I am writing this comment and this `big-lego.kcl` is still not done rendering.
- Well it just finished and it finally let me click the original `cup.kcl` file

I do not think we can actually test this workflow within the E2E test because swapping from a big file to a small file will takes minutes for it to actually finish. The codes doesn't seem like it is properly calling the code to cancel the previous file and load the new one. 

Shouldn't the workflow when clicking a file
- Cancel render of previous file
- Load new file
- Render new file

**Comment by nadr0** [comment]
Created related issue before I can implement these E2E tests. https://github.com/KittyCAD/modeling-app/issues/3686
