### ISSUE TITLE
Electron tests: text-to-cad file creation, navigation, and deletion behavior

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#3495]
Original PRs #3299 and #3448:

- [ ] Test for file creation on acceptance
- [ ] Test for file navigation on acceptance
- [ ] Test for file deletion on rejection

**Comment by franknoirot** [comment]
Reassigned in the spirit of cross pollination

**Comment by nadr0** [comment]
I have locally tested these workflows to create a testing suite. I wanted to provide some more details on the current workflow.

> Test for file creation on acceptance
The file is automatically created. The user does not need to press the accept button. 

> Test for file navigation on acceptance
The file can be navigated to since it is already created. They can navigate and view the file before clicking accept. 

I don't think anything needs to change, I wanted to clarify that creation and navigation can happen before acceptance, you do not need to hit accept in the toast box.
