### ISSUE TITLE
"Exported Successfully" when cancelling export

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#3542]
### Description
Super tiny thing, but we toast "exported successfully" when the user selects "cancel"

### Version
v0.24.12

### Recording
https://github.com/user-attachments/assets/621143ef-622c-4e22-8c09-f4ac7ad2ae37

**Comment by jessfraz** [comment]
i would consider this a bug

**Comment by jessfraz** [comment]
because it is not correct behavior

**Comment by jgomez720** [comment]
ah, alrighty

**Comment by jessfraz** [comment]
i literally had no idea there was a different menu to hit export from? why so many ways to export, is that code path tested? maybe we lessen the different ways to do things? idk why we need three ways to export something

**Comment by jgomez720** [comment]
wait how are you exporting? I only know the top left

**Comment by jgomez720** [comment]
oh I found the other button

**Comment by Irev-Dev** [comment]
Going to close this since it duplicates #3542

**Comment by franknoirot** [comment]
It's the same code path however you get to export:
1. [From the project menu](https://github.com/KittyCAD/modeling-app/blob/main/src/components/ProjectSidebarMenu.tsx#L151-L155)
2. [From the sidebar](https://github.com/KittyCAD/modeling-app/blob/main/src/components/ModelingSidebar/ModelingSidebar.tsx#L49-L52)

The success toast is firing because there was no failure during the export, and that is a "success" as far as [these lines](https://github.com/KittyCAD/modeling-app/blob/main/src/components/ModelingMachineProvider.tsx#L458-L467) are concerned. I need to see how to receive a signal from the OS export UI that it was either a cancellation or a submission, because right now we only get back a "done" or "error".

**Comment by franknoirot** [comment]
Hell yeah there's a `canceled` property on the returned object https://www.electronjs.org/docs/latest/api/dialog#dialogshowsavedialogwindow-options

**Comment by franknoirot** [comment]
Ah dang I wanted to add an E2E test and I just remembered we can't interact with the OS dialog 💀. I'll add it to #3588
