### ISSUE TITLE
make sure we have test coverage on exporting a file from dropdown menu / command bar

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#3582]
I know theres coverage on the button in the side bar but idk about others

**Comment by jessfraz** [comment]
this might not need a test, its just a sanity check of someone going thru and making sure we are covered

**Comment by Irev-Dev** [comment]
@jessfraz there's three an two are tested

`exports of each format should work` in `e2e/playwright/snapshot-tests.spec.ts` tests with the dropdown menu

and `Can export from electron app` in `e2e/playwright/projects.spec.ts` tests with the export button

but those buttons just open the command bar anyway so I think we good but I'll add a test.

Some details `e2e/playwright/snapshot-tests.spec.ts` tests all formats by exporting than using the cli to commit a image of the file as a sanity check

`e2e/playwright/projects.spec.ts` only asserts the file size and only tests gltf, I thought doing the whole screen shot was crazy doubling up since the fact that it wrote the file means that path works, the format and the rest is all engine stuff that we have coverage from `e2e/playwright/snapshot-tests.spec.ts`

Is that good with you? (and that's what I'll do for the cmd bar one too)

**Comment by jessfraz** [comment]
yeah for sure i just need for sanity at least one test for each hitting button even if they have the same path after that, who knows if button breaks lol

**Comment by Irev-Dev** [comment]
sweet sweet sweet.
