### ISSUE TITLE
Show the Device Activation code when users log in

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#3721]
When users log into the modeling app, they click on their OAuth provider (e.g. Google) and then sign in, and then they see this.

<img width="724" alt="Screenshot 2024-08-29 at 12 04 48 PM" src="https://github.com/user-attachments/assets/8accd8ee-04ec-4d67-9d56-822bbab27be3">

Users have to ignore the big code, and instead press the little continue button.

This is confusing! I still have to override my instinct to copy that code and paste it into the app somewhere. If this information is never used by the modeling app, then logging into the modeling app shouldn't show it.

We should make a second kind of login API/page which _doesn't_ show you this code, and then the modeling app should use that instead.

**Comment by jessfraz** [comment]
The whole point is you are supposed to verify the code with the one in the app to make sure no one is spying. We can’t hide in , in fact we need to show the code to verify from the modeling app

**Comment by jessfraz** [comment]
Cc @iterion @franknoirot

**Comment by jessfraz** [comment]
For whoever picks this up, the oauth2 device verification code will be provided to the client we just have to show it back to them, we do this in the cli for reference

**Comment by jtran** [comment]
I agree. It's like a Norman door. The page should have a single call to action that is the next step.

If the user needs to verify that it matches, the button label should be "It matches" or something indicating that the user should have actually verified something before clicking.

**Comment by jessfraz** [comment]
yeah the problem was in modeling-app we don't show them the code to verify haha but we need to!

**Comment by franknoirot** [comment]
Yeah showing the code to the user doesn't seem straightforward to me. Right now `window.electron.login()` awaits for the entirety of the auth flow, so there's no opportunity to show the device token in the middle. I think we need to separate it out so that there is a call before it that actually initiates the login sequence and passes back the device token to the frontend—maybe this could continue to be called `getDeviceToken()`—and then another function actually opens the browser and runs the auth flow, maybe called `login()`

**Comment by franknoirot** [comment]
Okay performing part of this splitting operation was easy. The remaining issue is that I cannot pass the `handle`—which contains the `user_code` I need to display—across the boundary of `ipcMain` because it is a class, not a JSON-serializable thing. And I need the `.poll()` method on this class to do the final login step.
