### ISSUE TITLE
clicking and rotating model in a crazy way can cause a backup queue

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#3745]
If you click and move the model consistently over around 60 seconds, continuously rotating, like go crazy with your mouse, eventually events will get backed up and if you let go you'll see the events queued up still going

so could be on the front end side
or could be on the engine side its getting queued up

**Comment by franknoirot** [comment]
I feel pretty confident that this was fixed with the v0.25.1 release thanks to @lf94's PR #3825. Here is a demo of the behavior that was giving issues, no longer seeing any sort of backup.

https://github.com/user-attachments/assets/f6cc63c5-4b1e-4812-bf63-fdc8c0eb9c1a

I'll assign this to @lf94 to mark as Done if he agrees.

**Comment by lf94** [comment]
lmfao seeing the camera shake is great in the video 😆 

Yep I'm not noticing any backup in the queue either, so let's close.
