### ISSUE TITLE
optimizing perf of model loading

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#3799]
today this is not bad but there are things that can be improved, especially as we get into larger models:

https://github.com/user-attachments/assets/7d2a6e42-07c9-4aae-95d2-a2f3f771eb1b

first we need to measure (some ideas):
1. time to app open
2. time to code load
3. time to syntax highlight
4. time to stream load
5. time to model load

I like how vscode priotizes time to code load, _then_ does syntax highlighting etc, more info here: https://www.electronjs.org/docs/latest/tutorial/performance

I bet we can make stream load faster too, cc @paultag @iterion 

anyways considering thus far we have put zero effort into this i am sure it can be fast as fuck with actual effort

**Comment by nadr0** [comment]
I'll be opening a PR for this feature.


Here is the output when I run `./out/Zoo\ Modeling\ App-linux-x64/zoo-modeling-app ~/Documents/zoo-modeling-app-projects/default/cube.kcl ` from a locally packaged binary from `yarn tron:package`

```
| name                           | startTime     | delta   | total    |
| ------------------------------ | ------------- | ------- | -------- |
| code/timeOrigin                | 1728674145077 | 0.00    | 0.00     |
| code/willAuth                  | 1728674153072 | 7995.00 | 7995.00  |
| code/willLoadFile              | 1728674153121 | 49.00   | 8044.00  |
| code/didAuth                   | 1728674153423 | 302.00  | 8346.00  |
| code/startInitialEngineConnect | 1728674153472 | 49.00   | 8395.00  |
| code/didLoadFile               | 1728674153487 | 15.00   | 8410.00  |
| code/willSyntaxHighlight       | 1728674153933 | 446.00  | 8856.00  |
| code/didSyntaxHighlight        | 1728674153934 | 1.00    | 8857.00  |
| code/endInitialEngineConnect   | 1728674154410 | 476.00  | 9333.00  |
| code/startExecuteAst           | 1728674154916 | 506.00  | 9839.00  |
| code/endExecuteAst             | 1728674155454 | 538.00  | 10377.00 |
```

- time to app open -> `didLoadFile` because we are loading the `/file` route. 
- time to code load -> `startExecuteAst` because this is when the code can actually run
- time to syntax highlight -> `willSyntaxHighlight` and `didSyntaxHighlight`
- time to stream load -> `startInitialEngineConnect` and `endInitialEngineConnect`
- time to model load -> `endExecuteAst`

I added a few other marks in the application to help understand **time to app open**.
