### ISSUE TITLE
3) Extend 1) to allow selecting edges as well as the sketch

### ISSUE THREAD

**Issue by nadr0** [KittyCAD/modeling-app#3801]

**Comment by nadr0** [comment]
accidentally created this issue from the original ticket when I clicked the little UI button to make an issue. I am closing this.

**Comment by Irev-Dev** [comment]
It was always going to get turned into an issue at some point. Do you think we start working on this @nadr0 ?

Atm it only makes sense to select solid3d edges, but we need https://github.com/KittyCAD/engine/issues/2539 in before we can select solid2d edges and segments that haven't been extruded, but might still be worth working on this?

I think the main thing would be adding selection of edges to the cmd bar (not sure how involved that would be) but you saw with the MVP selecting a solid2d since it's the same as extrude, but we haven't done selecting edges in the cmdbar anywhere else before. Than ofcourse this updating the code-mod, not to hard-code the x-axis in.

**Comment by nadr0** [comment]
Yeah this makes sense to work on as the next ticket after looking at the parent issue.

I think it is worth implementing solid3d edges, if the code we write for that will support solid2edge and segments in the future that is a win. 

Goals would be?

- [ ] allow selecting of solid3d edges
- [ ] update command bar to support faces or edges
- [ ] code mode to not hard code x axis

**Comment by Irev-Dev** [comment]
Yeah that sounds right.

I'll just point out that, something you and I found while paring

```ts
Revolve: {
    description: 'Create a 3D body by rotating a sketch region about an axis.',
    icon: 'revolve',
    needsReview: true,
    args: {
      selection: {
        inputType: 'selection',
        selectionTypes: ['extrude-wall', 'start-cap', 'end-cap'],
```

I think there's something wrong with whatever selectionTypes is doing here and maybe by extension the function `getSelectionType`. This was existing with extrude and got grandfathered into the revolve MVP, but it doesn't make sense because the user is selecting a closed profile/sketch, not any of `['extrude-wall', 'start-cap', 'end-cap']` so I'm not sure what's happening, @franknoirot might have a bit more context than us.

I bring it up, because I'm guessing we'll want `selectionTypes: ['edges']` or similar for this next step.

**Comment by franknoirot** [comment]
Yeah 100% this was a hack from back in the day because of some limitations with our selection setup when the selection input component for the command palette was created. I don't think I had a way at the time to filter the selection type or get accurate selection types like a simple `'face'`, so this has been the heirloom. It's something that I think @max-mrgrsk may have an update to in his Fillet point-and-click work, because he had to have a selection argument in the command bar that filtered to `'edges'` already.

**Comment by Irev-Dev** [comment]
BTW, Mike has a PR up for the dry run stuff as well, see we can likely integrate that in at the same time
https://github.com/KittyCAD/engine/pull/2659

**Comment by nadr0** [comment]
@franknoirot 
> ['extrude-wall', 'start-cap', 'end-cap']

This should be wrong for `extrude` as well not just revolve. When you read that block of code for configuration, it says to do an extrude your selection types are `['extrude-wall', 'start-cap', 'end-cap']` which does not make sense because that is a product of an extrude.

If we change this, we would want to do it for both revolve and extrude.

**Comment by nadr0** [comment]
After discussing with the team today I came up with a plan

- [ ] get tag from line or auto generate a tag e.g (`$myTag` or `$edge001`)
- [ ] Determine if the edge is the original edge or an `getOppositeEdge`
- [ ] Pass the tag to the `axis` in the `revolve` command

Other workflow issues that need to be resolved
- [ ] selection of the local X and Y axis to keep the same selection workflow similar to the edges
