### ISSUE TITLE
opening a project going from dark mode to light mode does not work well

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#3805]
either we should fix it or remove the ability to have different themed projects 

https://github.com/user-attachments/assets/9cf7e149-e530-4753-b5ea-77c56974ce71

**Comment by adamchalmers** [comment]
I think Dark/Light Theme should be an app-wide setting, not per-project. I've never seen any other software offer per-project light/dark theme.

**Comment by franknoirot** [comment]
Yeah I agree, and we turned off Theme as a project-level setting in #3312. I think the settings parsing system would still pick it up though, what that PR did was just turn off users' ability to change the setting, not whether the app would respect it. @jessfraz does that project you opened in your video have a theme setting in its `project.toml`?

I think the visual regression is not really the result of that, but rather due to some hasty changes I made to global CSS while trying to create #3794. I suspect light OS + dark theme and dark OS + light theme are what is happening here. It's the same issue I'm trying to fix for Josh.
