### ISSUE TITLE
loft() giving error that doesn't seem to make sense

### ISSUE THREAD

**Issue by yeroca** [KittyCAD/modeling-app#3895]
I have created two sketches - sketch007 and sketch010 - of rectangles on parallel planes, separated by 3mm.  Lofting sketch007 to sketch010 gives an API error when the loft() call is uncommented.

![image](https://github.com/user-attachments/assets/69b23532-6cb4-46da-81a4-6c1ab8d9c333)

Both sketches are closed polygons, so I don't know what this message means.  Maybe it's my misunderstanding. 

![Screenshot](https://public.blob.zoo.dev/d473f53b-b013-48b9-ad8a-b5beea0c9c46/modeling-app/coredump-5aee961f-4a43-4ca3-9179-51432ca688ce-screenshot.png)

<details>
<summary><b>Core Dump</b></summary>

[coredump-5aee961f-4a43-4ca3-9179-51432ca688ce.json](https://public.blob.zoo.dev/cbbbb9a4-cf77-44d4-89f1-9d334e762ef8/modeling-app/coredump-5aee961f-4a43-4ca3-9179-51432ca688ce.json)

Reference ID: 5aee961f-4a43-4ca3-9179-51432ca688ce
</details>

<details>
<summary><b>KCL Code</b></summary>

```kcl
const holeFudge = 0.4
const frontBarD = 5.0
const yBarD = 6.7
const lowerBlockTransHoleD = frontBarD + holeFudge
const lowerBlockTransHoleR = lowerBlockTransHoleD / 2
const upperBlockLongHoleD = yBarD + holeFudge
const upperBlockLongHoleR = upperBlockLongHoleD / 2
const upperBlockTransHoleD = yBarD + holeFudge
const upperBlockTransHoleR = upperBlockTransHoleD / 2
const tubeClr = 1.5
const lowerBlockH = lowerBlockTransHoleD + 2 * tubeClr
const upperBlockH = upperBlockLongHoleD + 2 * tubeClr
const elevateH = 5
const upperBlockL = 25
const lowerBlockL = 70
const blockSz = max(upperBlockH, lowerBlockH)

const slotL = 10
const slotH = 1

fn slot = () => {
  const slotSketch = startSketchOn('XZ')
    |> startProfileAt([0, -(blockSz - slotH) / 2], %)
    |> xLine(slotL, %)
    |> yLine(-slotH, %)
    |> xLine(-slotL, %)
    |> close(%)
  return slotSketch
}
const sketch001 = startSketchOn('XZ')
  |> startProfileAt([0, 0], %)
  |> yLine(blockSz, %, $edgeA)
  |> xLine(blockSz, %, $edgeB)
  |> yLine(-blockSz, %, $edgeC)
  |> xLine(upperBlockL - blockSz, %, $edge1)
  |> yLine(-(elevateH + blockSz), %, $edge2)
  |> xLine(lowerBlockL - blockSz, %, $edge3)
  |> yLine(-blockSz, %, $edge4)
  |> xLine(-lowerBlockL, %, $edge5)
  |> yLine(blockSz + elevateH, %, $edge6)
  |> xLine(-(upperBlockL - blockSz), %, $edge7)
  |> lineTo([profileStartX(%), profileStartY(%)], %, $seg01)
  |> close(%)
  // |> hole(slot(), %)
  |> hole(circle([blockSz / 2, blockSz / 2], upperBlockTransHoleR, %), %)
  |> hole(circle([
       upperBlockL + lowerBlockL - blockSz - lowerBlockTransHoleR - tubeClr,
       -(blockSz + elevateH + blockSz / 2)
     ], lowerBlockTransHoleR, %), %)
const rad = 3
const extrude001 = extrude(blockSz, sketch001)
  |> fillet({
       radius: rad,
       tags: [
         getNextAdjacentEdge(edgeA),
         getNextAdjacentEdge(edgeB),
         getNextAdjacentEdge(edgeC),
         getNextAdjacentEdge(edge2),
         getNextAdjacentEdge(edge3),
         getNextAdjacentEdge(edge4),
         getNextAdjacentEdge(edge5),
         getNextAdjacentEdge(edge6)
       ]
     }, %)

const sketch006 = startSketchOn(extrude001, 'START')
  |> startProfileAt([-25, 0], %)
  |> xLine(upperBlockL, %)
  |> yLine(-upperBlockH, %)
  |> xLine(-upperBlockL, %)
  |> lineTo([profileStartX(%), profileStartY(%)], %)
  |> close(%)

const sketch007 = startSketchOn(extrude001, 'END')
  |> startProfileAt([0, 0], %)
  |> xLine(upperBlockL, %)
  |> yLine(-upperBlockH, %)
  |> xLine(-upperBlockL, %)
  |> lineTo([profileStartX(%), profileStartY(%)], %)

const frontFaceOff = blockSz
const backFaceOff = 0
const bevel = 3
const plane1 = offsetPlane('XZ', frontFaceOff + bevel)
const sketch010 = startSketchOn(plane1)
  |> startProfileAt([0,-bevel], %)
  |> xLine(upperBlockL, %)
  |> yLine(-(upperBlockH - 2 * bevel), %)
  |> xLine(-upperBlockL, %)
  |> lineTo([profileStartX(%), profileStartY(%)], %)

//const loft001 = loft([sketch007, sketch010])

const sketch004 = startSketchOn(extrude001, 'END')
  |> startProfileAt([49.92, 13.58], %)
const sketch003 = startSketchOn(extrude001, 'END')
const sketch002 = startSketchOn(extrude001, seg01)
  |> startProfileAt([0, 0], %)
  |> circle([blockSz / 2, -blockSz / 2], upperBlockLongHoleR, %)
const extrude2 = extrude(-upperBlockL, sketch002)
const sketch005 = startSketchOn('XZ')

```
</details>

**Comment by gserena01** [comment]
Hi! Thank you for your patience with us as we get back to you!

I just took a look at your kcl, and it looks like there was a misinterpretation of our error (and maybe also an opportunity for us to be more clear with our users!). 

The error says you need a closed path, aka a Solid2D. This literally means that you need to use `    |> close(%)
` on the sketch to create a solid, 2-dimensional object.

I modified your kcl to use this, but I had to remove the fillet because the operation failed (excuse my uneven comment //'s). Don't worry, we have another issue open to provide more meaningful fillet errors, so we will get to the bottom of that soon!

`const holeFudge = 0.4
const frontBarD = 5.0
const yBarD = 6.7
const lowerBlockTransHoleD = frontBarD + holeFudge
const lowerBlockTransHoleR = lowerBlockTransHoleD / 2
const upperBlockLongHoleD = yBarD + holeFudge
const upperBlockLongHoleR = upperBlockLongHoleD / 2
const upperBlockTransHoleD = yBarD + holeFudge
const upperBlockTransHoleR = upperBlockTransHoleD / 2
const tubeClr = 1.5
const lowerBlockH = lowerBlockTransHoleD + 2 * tubeClr
const upperBlockH = upperBlockLongHoleD + 2 * tubeClr
const elevateH = 5
const upperBlockL = 25
const lowerBlockL = 70
const blockSz = max(upperBlockH, lowerBlockH)

const slotL = 10
const slotH = 1

fn slot = () => {
  const slotSketch = startSketchOn('XZ')
    |> startProfileAt([0, -(blockSz - slotH) / 2], %)
    |> xLine(slotL, %)
    |> yLine(-slotH, %)
    |> xLine(-slotL, %)
    |> close(%)
  return slotSketch
}
const sketch001 = startSketchOn('XZ')
  |> startProfileAt([0, 0], %)
  |> yLine(blockSz, %, $edgeA)
  |> xLine(blockSz, %, $edgeB)
  |> yLine(-blockSz, %, $edgeC)
  |> xLine(upperBlockL - blockSz, %, $edge1)
  |> yLine(-(elevateH + blockSz), %, $edge2)
  |> xLine(lowerBlockL - blockSz, %, $edge3)
  |> yLine(-blockSz, %, $edge4)
  |> xLine(-lowerBlockL, %, $edge5)
  |> yLine(blockSz + elevateH, %, $edge6)
  |> xLine(-(upperBlockL - blockSz), %, $edge7)
  |> lineTo([profileStartX(%), profileStartY(%)], %, $seg01)
  |> close(%)
  // |> hole(slot(), %)
  |> hole(circle({center: [blockSz / 2, blockSz / 2], radius: upperBlockTransHoleR}, %), %)
  |> hole(circle({center: [
       upperBlockL + lowerBlockL - blockSz - lowerBlockTransHoleR - tubeClr,
       -(blockSz + elevateH + blockSz / 2)
     ], radius: lowerBlockTransHoleR}, %), %)
const rad = 3
const extrude001 = extrude(blockSz, sketch001)
  ///|> fillet({
   ///    radius: rad,
    ///   tags: [
      ///  getNextAdjacentEdge(edgeA),
    ///     getNextAdjacentEdge(edgeB),
       ///  getNextAdjacentEdge(edgeC),
///         getNextAdjacentEdge(edge2),
   ///      getNextAdjacentEdge(edge3),
      ///   getNextAdjacentEdge(edge4),
 ///        getNextAdjacentEdge(edge5),
    ////     getNextAdjacentEdge(edge6)
 ///      ]
    //// }, %)

const sketch006 = startSketchOn(extrude001, 'START')
  |> startProfileAt([-25, 0], %)
  |> xLine(upperBlockL, %)
  |> yLine(-upperBlockH, %)
  |> xLine(-upperBlockL, %)
  |> lineTo([profileStartX(%), profileStartY(%)], %)
  |> close(%)

const sketch007 = startSketchOn(extrude001, 'END')
  |> startProfileAt([0, 0], %)
  |> xLine(upperBlockL, %)
  |> yLine(-upperBlockH, %)
  |> xLine(-upperBlockL, %)
  |> lineTo([profileStartX(%), profileStartY(%)], %)
  |> close(%)

const frontFaceOff = blockSz
const backFaceOff = 0
const bevel = 3
const plane1 = offsetPlane('XZ', frontFaceOff + bevel)
const sketch010 = startSketchOn(plane1)
  |> startProfileAt([0,-bevel], %)
  |> xLine(upperBlockL, %)
  |> yLine(-(upperBlockH - 2 * bevel), %)
  |> xLine(-upperBlockL, %)
  |> lineTo([profileStartX(%), profileStartY(%)], %)
  |> close(%)

const loft001 = loft([sketch007, sketch010])

const sketch004 = startSketchOn(extrude001, 'END')
  |> startProfileAt([49.92, 13.58], %)
const sketch003 = startSketchOn(extrude001, 'END')
const sketch002 = startSketchOn(extrude001, seg01)
  |> startProfileAt([0, 0], %)
  |> circle({center: [blockSz / 2, -blockSz / 2], radius: upperBlockLongHoleR}, %)
const extrude2 = extrude(-upperBlockL, sketch002)
const sketch005 = startSketchOn('XZ')

`


Because this should resolve your issue, I'm marking it as closed!
