### ISSUE TITLE
Small line segments should keep arrow heads at least.

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#3966]
See video:

https://github.com/user-attachments/assets/b000f64f-bc43-4efd-ba63-a22562b28304

It makes it not obvious these are individual line segments.

**Comment by lf94** [comment]
Know what I'm already in this area of code, I'll quickly fix it

**Comment by Irev-Dev** [comment]
Arrow heads act as the handle te the segment the intention was to hide the handle when the line get's too small, since once they're too small the user starts being more likely to click the wrong thing and get frustrated, the same way that it adding an extra segment when you didn't intend it is trusting.

Same comment as https://github.com/KittyCAD/modeling-app/issues/3974

> In the extreme case where there's 100 segments in a 5x5 pixel space, showing everything would be cluttered and there's no way the user would be able to click on what they actually intended to interact with.

**Comment by Irev-Dev** [comment]
I'm just want to be cautious, if the current UI is bad, I wouldn't want to fix it with a series of haphazard band aid fixed ya know. and just because this is "fixing" something that was intentional, I worry about it.

**Comment by lf94** [comment]
You know what, I'll close. My proposal here was arrowheads but evidently it is not a valid solution. I'll revert the change locally.
