### ISSUE TITLE
Snag while opening default project

### ISSUE THREAD

**Issue by pierremtb** [KittyCAD/modeling-app#4215]
Happened with @franknoirot and Oscar at 10:20.

**Comment by pierremtb** [comment]
@franknoirot what we just talked about: after a few steps of onboarding (up to the kcl stage) and hitting Dismiss. Oscar saw the buttons at the top getting all messed up and was in a weird state.

**Comment by pierremtb** [comment]
Not really able to reproduce on macOS after a few attempts

**Comment by franknoirot** [comment]
Okay thanks for trying to reproduce. I'm going to try reproducing more today, particularly with no settings files (blank slate) and on Windows.

**Comment by franknoirot** [comment]
Yes this is reproducible on MacOS too. It only occurs when being redirected to the onboarding, so you have to reset your onboarding state or delete your settings to get it. I need to:
- [ ] Root cause it
- [ ] Fix it
- [ ] Figure out why the playwright tests in [`onboarding-tests.spec.ts`](https://github.com/KittyCAD/modeling-app/blob/main/e2e/playwright/onboarding-tests.spec.ts) don't capture this regression.
