### ISSUE TITLE
The concept of idle 

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#563]
In order to save on compute we need the concept of idle where like the stream disconnects but we store a frame of the last model and obviously their code so they aren’t freaked out 

but maybe the model not the code has a dark opacity modal over it like “reconnect” or something 

idk 

should support:

- laptop close and open
- tab focus and unfocus
- tab focus. but idle for X time

@franknoirot for ideas and @paultag for reconnect disconnect thoughts

**Comment by paultag** [comment]
@indirectlylit reported in https://github.com/KittyCAD/modeling-app/issues/989 a large data download that was due to an 18 hour session streaming WebRTC video down from the engine. This isn't ideal for our engines, and not for users, especially if they're not aware it's still running.

**Comment by Irev-Dev** [comment]
Some notes on FE implementation

- You can take frames from a video stream and slap it onto a canvas, we could use that when the user hasn't interacted with the app in 5mins or so and keep their last frame visible with a message "connection in idle mode, click here to reconnect" or similar.

Nice to have, does not need to be in the initial implementation of idle mode. We can return users back to sketch mode if that's what they were doing when they either stopped using the app but would work the same for the engine crashing, or wifi dying.
- When the engine boots up, it will need to re-execute, so ids will change, but because the sketchMode is based around a pathToNode I can just quickly put the user back into that node using the original pathToNode to grab the updated ids from the artifactMap, so it will be all good.

Also we can return the user's camera back to where it was on engine reboot as we have context of the camera position

https://github.com/KittyCAD/modeling-app/assets/29681384/71347be5-9031-407d-8ab5-39adc67b7e90

**Comment by Irev-Dev** [comment]
For the above, I think points 2) and 3) should be something I implement, I can do this at any time because really it's the same as making the app robust to re-connections.

**Comment by jessfraz** [comment]
from discord: "I notice that when the Zoo app is idle, it still consumes a ton of CPU.  Is this a known issue?"

something to look into as a part of this, i would presume network not cpu

**Comment by jessfraz** [comment]
ahhh makes sense

**Comment by lf94** [comment]
It's kind of been said already but to clarify:

1. We have a "light idle" where we pause the stream after each operation
2. We have a "heavy idle" where we kill the remote engine instance after some time (2-3 minutes? adjustable)

**Comment by jessfraz** [comment]
on windows ive noticed the stream will disconnect, like maybe a windows specific thing where it kills a windows access but idle mode will fix but its very annoying for windows users, just placing this here to up the priority a bit

**Comment by lf94** [comment]
After further thinking I think a stream pause wouldn't really do much. Instead I think it'd be more effective to completely teardown the connection after ~20 or ~30 seconds of inactivity and freeze frame the last thing seen. As soon as there is any mouse movement or a click or keyboard, it will reestablish connection (but not show a "loading")

**Comment by lf94** [comment]
I might hammer this out in the next hour

We actually got the "idle on tab switch / window switch" done in https://github.com/KittyCAD/modeling-app/pull/2915
