### ISSUE TITLE
if you are in sketch mode and switch projects you are still in sketch mode and state is efffed

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#619]
https://github.com/KittyCAD/modeling-app/assets/1445228/5b93fa20-621c-4ce2-ac90-c18e3285ef09

**Comment by Irev-Dev** [comment]
Not resolved by initial xstate migration

**Comment by jessfraz** [comment]
what if we disable going home whiile in sketch mode, seems like a good way to solve?

**Comment by jessfraz** [comment]
having a tauri test for this eventually will be nice, i know we alll know this but im saying it so later when i search "tauri test" ill find this issue

**Comment by franknoirot** [comment]
Yeah I'm thinking the latter, that we should have a teardown in modelingMachine that fires in the event of a navigation

**Comment by jessfraz** [comment]
i like that def cleaner

**Comment by franknoirot** [comment]
That initial video on this issue is so gnarly, your state got so messed up. I've been trying to reproduce it this morning and haven't been able to. Here's what I see:

https://github.com/KittyCAD/modeling-app/assets/23481541/63c53a0d-a3e9-404c-94c3-2f7bd38a82ba

That being said, it does make me nervous that we don't have anywhere in the codebase that just fires the `"Cancel"` event before unmounting. The `ModelingMachineProvider` is torn down when the user navigates home, but the engineConnection lives on as a singleton, so I think this is a sound practice. Here I am adding that, with no perceptible difference at the moment, but I'll open a PR with the addition.


https://github.com/KittyCAD/modeling-app/assets/23481541/d6220ca4-a1e8-48a0-b063-165d11cec539
