### ISSUE TITLE
RTCPeerConnection error on Linux builds

### ISSUE THREAD

**Issue by pierremtb** [KittyCAD/modeling-app#625]
![image](https://github.com/KittyCAD/modeling-app/assets/10795683/280ee79f-ad9e-45b7-a989-88ac0c112089)

**Comment by eric-schleicher** [comment]
ok, registering same issue on fedora38 (nobara).

![image](https://github.com/KittyCAD/modeling-app/assets/8261783/5ebcecc7-8d73-4368-ac75-b7a9f6c5ee17)

I'm 0-2 trying windows and linux in rapid succession.  will try the browser app

**Comment by adamchalmers** [comment]
@JonasKruckenberg Hi! FYI, the comment from @paultag directly above is what I was talking with you about on twitter.

**Comment by JonasKruckenberg** [comment]
Linux am I right? 🙃 Sorry that you guys had to go through this, but seems like you figured it out!

**Comment by paultag** [comment]
@JonasKruckenberg to be fair it only took a few hours (although I have a hunch being a Debian Developer helped a lot here) -- it really wasn't an issue or even something I felt the need to file an issue about with Tauri.

That being said, just to communicate more explicitly the thing we're waiting for on Linux support (or rather; for me to start working on Linux support for KCMA) is either a release of tauri classic / 1.0 (given we're on `version = "1.5.0"` today), or 2.0 when we'd likely have to undergo porting work, either version of which, which brings in a `wry` version that in turn brings in a `libwebkit2gtk` version of `4.1` rather than `4.0`, including the exposed `set_enable_webrtc` flag on the Settings object.

Thanks for maintaining Tauri, it's great stuff!

**Comment by paultag** [comment]
As an update for folks watching the issue: I just checked on this issue again since we updated Tauri at some point.

We're still pinned against `webkit2gtk = { version = "0.18.2", features = [ "v2_22" ] }`  via tauri, which is older than the changes we need behind feature `v2_38` in `webkit2gtk`. Still in a holding pattern here!

**Comment by dcl** [comment]
are there any updates on this? it looks like tauri v2 pins `webkit2gtk = { version = "=2.0.1", features = [ "v2_38" ] }`, so #1400 should have unblocked the issues mentioned upthread

**Comment by paultag** [comment]
@dcl so sorry -- haven't had a chance to reply before now. We've been working to get this resolved; we (KittyCAD/Zoo) paid for some upstream work to fix some related bugs in upstream gstreamer/webkit2gtk after it's been isolated, and we're looking a LOT better. They did a TON of great work and we're close to having first-class Linux builds. Hang tight!

**Comment by jessfraz** [comment]
with the latest release we FINALLY HAVE linux builds, thank you electron
