### ISSUE TITLE
"Replay Onboarding" button does not appear when launching Settings from Home menu

### ISSUE THREAD

**Issue by greg-kcio** [KittyCAD/modeling-app#728]
Windows, v0.9.2: I wanted to go through onboarding again, and couldn't find the Replay Onboarding button in the settings menu when accessing settings from the Home screen. The button is only visible when accessing the settings while a project is open.

![image](https://github.com/KittyCAD/modeling-app/assets/29708191/6ff5e7d5-e46a-415c-9212-d16019a2ecac)

**Comment by franknoirot** [comment]
Okay my fix is just a smidge hacky in that it doesn't resolve the global/file settings divide like I'd like to yet:
1. I like your idea of having the new project be called "Tutorial Project", but I appended "$nn" to allow for multiples to be made with no problems. 
2. I'm hesitant to add Save and Save As just yet because I think that without autosave (and by extension auto-create) behavior I think we're forcing people to opt into saving and I think that should be handled by the app in nearly all cases. Save As is just Copy + Rename in my mind.
