### ISSUE TITLE
Windows: Startup:  Path not allow of configured scope.

### ISSUE THREAD

**Issue by eric-schleicher** [KittyCAD/modeling-app#779]
![image](https://github.com/KittyCAD/modeling-app/assets/8261783/ebf9990b-d43e-4ac5-88a6-b502d0acb2f3)

My documents folder is not on C and is in the root of another disk, so not sure if that's causing the issue.

**Comment by jgomez720** [comment]
Thanks for the report @eric-schleicher. 
@franknoirot let me know if this belongs to someone else.

**Comment by franknoirot** [comment]
Yeah appreciate it @eric-schleicher! I might need to tag in @pierremtb too if he has time, because I'm working on multi-file right now.

I do think you're correct and it's got something to do with [Tauri's fs API](https://tauri.app/v1/api/js/fs/#basedirectory), file permissions and determining the correct base directory.

**Comment by pierremtb** [comment]
@eric-schleicher @franknoirot thanks for the report and ping, happy to look into it.

@eric-schleicher Did you happen to change that directory or was it default (and the app simply never worked on your machine?)

My VM is also working off a different default drive than C 
![image](https://github.com/KittyCAD/modeling-app/assets/10795683/d57bc094-5a5c-41c5-825e-c777aa17ccb3)
