### ISSUE TITLE
`delete` key should delete the object from the scene when it is highlighted

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#782]

**Comment by franknoirot** [comment]
Behavior questions:
1. Should the `delete` key with an object selected remove any variables that aren't used anywhere else? 
2. For now should you only be able to `delete` bodies in default mode, segments/points in sketch mode?

**Comment by franknoirot** [comment]
First attempt at this works for any entity that's defined "inline" but not if they're generated from a user-created function:

https://github.com/KittyCAD/modeling-app/assets/23481541/8c892360-0449-4833-9de5-970edf159e73

I think we need to map entities to code ranges differently so that entities generated from user-authored functions resolve to their top-level constant declaration, not the startSketchOn call within the function. I'll post a comment to discuss in there but since I recorded this in Slack anyway I'll leave it here too
