### ISSUE TITLE
Code editor cursor is too dark in dark mode

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#812]
Cursor is too hard for people to see currently. Also I'm noticing that the pulse animation for the cursor that appears when the user isn't focused on the code pane is interfering with the normal pulsing animation whenever the user _is focused_ within it.

**Comment by jessfraz** [comment]
@franknoirot is this still true?

**Comment by Irev-Dev** [comment]
imo
https://github.com/KittyCAD/modeling-app/assets/29681384/fb5d6e3a-b8d3-44c7-acac-49a32a6e5248

**Comment by franknoirot** [comment]
That one is tough @Irev-Dev, because a text cursor is often the primary visual cue for having focus on an input. It is very confusing to see a cursor in a text box, type several characters, and only then realize that you have not focused the text editor.

**Comment by franknoirot** [comment]
Maybe it's the line highlighting that's contributing to the visual clutter? If we were to have a consistent logic of `text in focus === skinny cursor` and `text out of focus === block selection cursor`, and made that brighter and got rid of the full-line highlighting, would that help make things clearer?

I did address the original intent of this issue with https://github.com/KittyCAD/modeling-app/commit/3fdf7bd45e75063fdbe957c1cbc1fe2517a080d2#diff-3260a6f05315c0f783e44ed248b4708bf74b46e620b0137e3726a345b00ece0c, I should have tied them together.

**Comment by nadr0** [comment]
I'll be closing this issue since we can see the cursor within the dark mode in the editor as of now.

We can open any new issues around showing the block cursor highlighting and removing the line highlight when the code pane does not have focus, or other different workflows.

This bug was marked in the extermination station and it is completed. We discussed as a team and there was not any immediate work to be done.
