### ISSUE TITLE
command bar, clicking an item should also work

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#846]
if I click an item in the command bar it doesnt work, but figured in the future we would want this

**Comment by franknoirot** [comment]
I believe this is resolved, but let me know if you still can't click an item @jessfraz. I should write a test for this, so even if you can do it don't close this, I'll just rename it to "Write test for clicking a command bar item instead of keyboard interacting" or something.


https://github.com/KittyCAD/modeling-app/assets/23481541/6f172840-4e37-45fc-8f5d-0e64bb2382e2
