### ISSUE TITLE
before release, we should add holes to the onboarding bracket 

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#864]

**Comment by jgomez720** [comment]
I started this and realized that I can't make a bracket and holes, it has to be one or the other, unfortunately. (Technically, I could, but it would be a really roundabout solution that I don't want to show users, it would be sloppy).

The reason why:

Holes can only be coupled with an extrusion, like our mounting plate example:
![Screenshot 2023-10-18 at 6 15 38 PM](https://github.com/KittyCAD/modeling-app/assets/114548659/f9c0f886-25bf-4290-a529-61b75b785e05)

However, for the bracket, the holes would have to be created after the first extrusion, because the first extrusion makes the "L" shape as well as creates the fillets.
![Screenshot 2023-10-18 at 6 19 17 PM](https://github.com/KittyCAD/modeling-app/assets/114548659/2e3b1199-4e35-49da-896a-70fe8c3f2b63)

Once we have an extrude that can remove material this is super easy.
