### ISSUE TITLE
Batch modeling commands

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#914]
The engine now supports handling multiple commands in a single WebSocket message, which should be much faster!

We should update the frontend to take advantage of this. If you're drawing an octogon, don't send all 8 `lineTo` commands in their own WebSocket messages. Instead, send a single WebSocket message with all the commands.

The schema will be published soon, but basically the request type changes from `"modeling_cmd_req"` to `"modeling_cmd_batch_req"`. And the JSON object changes from 

```
{
  "cmd": {}, 
  "cmd_id": {}
}
```

to 

```
{ "requests": 
  [
    { "cmd": {}, "cmd_id": {} },
    { "cmd": {}, "cmd_id": {} }
  ]
}
```

The relevant API client part in Rust is [here](https://docs.rs/kittycad/latest/kittycad/types/enum.WebSocketRequest.html#variant.ModelingCmdBatchReq)

**Comment by lf94** [comment]
Is there proof that batching works well? From what I've observed, batching does not drastically increase throughput.

Additionally, you should be able to batch an entire model, which I've tried, but the engine is not happy with it. It should be possible to do because you can assign UUIDs to all pieces of the model before-hand so there's no need to do setup commands.
