### ISSUE TITLE
don't re-execute if ast doesnt change

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#959]
we had this logic js side previous to the xstate stuff and seem to have lost it in the merge

but it basically ensured we wouldnt re-execute on whitespace changes which is nice

@franknoirot said he thinks the ast is executing twice on load and this might prevent that as well

also sometimes on load it doesnt execute at all, anyways seems a bit brittle here

**Comment by franknoirot** [comment]
Here's a screenshare of my "double execute" experience, it seems to only happen on small models that load super quickly:

https://github.com/KittyCAD/modeling-app/assets/23481541/5e0af2dd-26ad-4101-addb-732b82208b08

**Comment by Irev-Dev** [comment]
https://github.com/KittyCAD/modeling-app/pull/997 fixes the double-execute, making small PRs over here. Looking into the execute on whitespace now.

**Comment by Irev-Dev** [comment]
Okay I'm stumped on the not executing if the AST hasn't changed.

I can see you added this Jess
<img width="599" alt="image" src="https://github.com/KittyCAD/modeling-app/assets/29681384/c854c3ce-e467-4a10-baed-7735e66fc07d">

But I don't understand how this worked, when I try and add the same logic the `JSON.stringify() === JSON.stringify` always comes back as false, and that makes sense to me because the change in white space might be captured in `nonCodeMeta` nodes, but also if the whitespace is added somewhere in the middle of the code, it's going to change the start-end ranges for all the preceding nodes.

I can add the stringify logic back in, but a more robust way of comparing the ASTs might be good. would this be something like implementing `std::cmp::PartialEq` on the AST struct? and it could ignore `nonCodeMeta` nodes and the `start` and `end` properties?

**Comment by Irev-Dev** [comment]
Ahh thanks for rubber ducking with me typing that help me figure something basic out.

If I format the code (but not the users code/state) before comparing the ASTs then it easy way to ignore most whitespace changes.

https://github.com/KittyCAD/modeling-app/assets/29681384/3a8033a1-73c0-41ae-a0b8-066c61786281

I'll probably go ahead and merge that, still not perfect so we can decide what we want to do as a long term ast comparison.

**Comment by Irev-Dev** [comment]
I'll close this with https://github.com/KittyCAD/modeling-app/pull/1002 since the description talks about previous to the xstate migration, but we can open it back up if we want to take a different approach with AST comparing.

**Comment by jessfraz** [comment]
ah i guess the new parser saves whitespace which i was not doing, cc @adamchalmers to verify

as in before i was nuking extra spaces and shit

**Comment by Irev-Dev** [comment]
This might be resolved by https://github.com/KittyCAD/modeling-app/issues/993
In that we could compare execution plans instead of ASTs?
