### ISSUE TITLE
KittyCAD execution plans

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#993]
# KittyCAD execution plans

## Problem

There's a few problems with the current KCL execution model.

1. Hard to integrate with batching. 
    - Because the KCL executor is a tree-walk interpreter (it walks through the AST), the executor only knows about one API call at a given time. This means it's never sure when to join multiple commands into a batch.
2. Cannot separate KCL from API calls
    - We often file bugs like "this KCL program isn't producing a reasonable model", and want to reproduce that bug in the engine. We don't want to copy the KCL source code into an engine test, because that would require importing all the KCL language tools into the engine, and I firmly believe that the engine should not know about KCL (separation of concerns). But this means we basically have to run the KCL model in KCMA, add print statements for each API call, and recreate them in an engine test. If there was some way to "compile" KCL into a list of engine API curls, we could just paste those curls into an engine unit test instead.

## Proposal

Currently the executor walks along the KCL syntax tree and executes it node-by-node. When the executor visits a node it might update some program memory, or make an API call, or both.

My proposal is we separate walking the AST from executing the program. The new system would walk the AST to produce an _execution plan_. Then later, it executes that plan. An execution plan is similar to an AST but it:

 - doesn't have any comments
 - coalesces many batchable API calls into one batched API call
 - does constant-time math (e.g. the AST for `const x = 3 * 4` has five nodes, but the execution plan removes this node entirely and just substitutes `12` everywhere that `x` appeared in the AST)
 - is a list, not a tree

## Why

 1. This should run faster than the current walk down the AST, because of batching
 5. The execution plan allows for concurrency: if your model is two cubes, each can be executed concurrently, speeding up your overall program.
 6. The execution plan is simpler than the AST, it doesn't have comment nodes or whitespace nodes.
 7. Invalid programs can be detected during the AST-to-Execution-Plan step. E.g. if the user divides by zero or tries to add a string to a number. The AST-to-EP becomes our semantic analysis step!
 8. This gives us a language-agnostic way to describe KittyCAD API calls for users that aren't using KCL. Essentially this is our own DSL for running a series of KittyCAD API calls. You could represent these as a list of `curl`s to run, but then you need bash to put the output of some API calls into the input of other API calls. We see this problem in our unit tests, which have to invent their own shitty pseudo-languages for describing KittyCAD API calls, so every unit test ends up taking 400 lines just to sketch and extrude a cube. But execution plans are language-agnostic, they could be used by the modeling app or by Lee's non-KCL stuff. Now, when a KCL program outputs something weird, we can copy the KCL's execution tree into a unit test in the engine.

## How

**(1)**: produce an unoptimized execution plan

 - Walk the AST
 - If you would ever make an API call, instead, append that call to the execution plan.
 - If you would ever execute math, instead, append "do this math" and that math expression to the execution plan.

This is very similar to the current executor (which also walks the AST) but instead of actually executing API calls, it just writes them to a list of API calls which will be executed in the future.

**(2)**:  optimize the execution plan

 - If you would ever do math, and that math doesn't rely on the output of an API call, instead just store that math in program memory and remove the math from the execution plan
 - If there's a consecutive sequence of API calls and they don't depend on the output of the preceding call, batch them.

**(3)**: execute

```rust
async fn execute(plan: Vec<(ExecutionStep, Destination)>) -> Result<()>

/// Stores the output of a math equation or an API call.
/// Basically like a CPU register, which stores the outputs of an CPU instruction or prepares inputs for other instructions.
struct Destination(usize);

enum ExecutionStep {
    /// Very similar to how the current executor works -- send some websocket request,
    /// represented by the ApiCall object. This code is already in kcma, just needs to be moved onto this new type.
    ApiCall(ApiCall),
    /// Run a math equation whose inputs are either the results of an API call, or other values in program memory.
    /// The results get stored in program memory.
    Math(Math),
}
```

## Examples

```kcl
const width = 20
const part001 = startSketchAt([0,0])
  |> lineTo([width, 0], %)
  |> lineTo([width, width], %)
  |> lineTo([0, width], %)
  |> lineTo([0,0], %)
  |> close(%)
  |> extrude(width, %)
```

This KCL program outputs an AST which looks like 

<img width="814" alt="Screenshot 2023-11-03 at 4 58 56 PM" src="https://github.com/KittyCAD/modeling-app/assets/5407457/87370dd0-aaa2-4924-a092-054713cc6d73">

**(1)**: Walk the tree to produce an unoptimized plan

The tree has two children, walk them. 

Child one outputs these execution steps:
 - Map "width" to register 1
 - Store number literal 20 in register 1

Child two outputs:
 - Call "start sketch" API endpoint, store output sketch group in register 2
 - Call "lineTo" API endpoint, using register 2 as arg 1, ignore API output, store new sketch group in register 3
 - Call "lineTo" API endpoint, using register 3 as arg 1, ignore API output, store new sketch group in register 4
 - Call "lineTo" API endpoint, using register 4 as arg 1, ignore API output, store new sketch group in register 5
 - Call "lineTo" API endpoint, using register 5 as arg 1, ignore API output, store new sketch group in register 6
 - Call "close" API endpoint, using register 6 as arg 0, ignore API output, store new sketch group in register 7
 - Call "extrude" API endpoint, using register 1 and 7 as arguments, ignore API output, store ExtrudeGroup in register 8.

**(2)**: Optimize the plan

The optimizer notices that there are many consecutive API calls which all ignore API output, and coalesces them into one step. It outputs an optimized plan:

 - Map "width" to register 1
 - Store number literal 20 in register 1
 - Call "lineTo" x4, "close" and "extrude" API endpoints in a batch, ignoring all their outputs, feeding the outputs into the following command's inputs until finally stored in register 2.

## Future work

- Reject invalid execution plans before execution starts even runs
    - Typecheck the execution plans (or typecheck the AST as you're outputting the execution plan)
    - Identify other types of invalid programs (e.g. divide-by-zero) 
    - This gives users faster feedback on their programs because they don't have to wait for a bunch of API calls before they discover their bugs
- Serialize execution plans into a text or binary format which can be copied into other projects (e.g. the engine) and deserialized to run a sequence of KittyCAD API calls, piping data appropriately between them.
    - KCMA could output the execution plan in the debug panel
    - This would let us reproduce user bugs in the engine much more easily
- (far future) Could identify places for concurrency and automatically parallelize CPU-intensive work (e.g. if the user is doing a lot of  tough math calculations, split them across multiple CPU cores) or concurrent execution threads in the engine (e.g. identifying instances of shapes and converting them into engine instances)

**Comment by adamchalmers** [comment]
@jessfraz @Irev-Dev

**Comment by notalfredo** [comment]
Ouuu this is cool, so the `execution plan` is some sort of `intermediate representation` ?

**Comment by adamchalmers** [comment]
Yeah, exactly.

**Comment by Irev-Dev** [comment]
Thanks Adam,

One thing I don't follow is why use a DSL instead of just an array of structs? I can see how the first is easier to read and therefore better for tests, but it also seems like we'll need another (though ofc simpler parser) and seems like the engine will still kinda need some language logic.


To take a stab at the representation to see if understand, while trying to think through what an execution plan would look like that does relying on results from API calls, for the following hypothetical kclScript

```typescript
// previous code created someSketch
const volume = 3 * 4
const area = getAreaOfSketch(someSketch) // <- this call expression makes a call to the engine
const height = volume / area
const theExtrude = extrude(height, someSketch)
```

the execution plan might look like??

```bash
// previous parts of the execution plane put a sketch in register 1
Call "getAreaOfSketch" API endpoint, using register 1 as arg 1, store output in register 2
Call "extrude" API endpoint, using divide(12, register 2) as arg1, using register 1 as arg 1
```

I did some math in line with `divide(12, register 2)` because that's needed right? since `3 * 4` can be substituted by `12` we have to retain the divide by since we don't have the volume/register 2, assuming I'm on the right track here how do we represent this? I thought function notation `divide(...), add(...)` etc might be a good balance of still being readable, but also keeping the parsing straightforward (since there's no precedence etc complexity), at worst it could like like `divide(powerOf(add(2, multiply(2, 3)), 2), add(1, register 3))`, maybe we could still allow multi-line formating if we want to be readable.

**Comment by adamchalmers** [comment]
## Thoughts on DSL

Thinking more I don't think we need a DSL, JSON will do just fine. Hear me out. I think we should use some execution plan format which has an in-memory representation (for production) and a canonical text format (for debugging) which can be de/serialized.

In the normal KCMA production compiler path, it would 

parse KCL into AST -> walk AST to make execution plan (in-memory) -> optimize execution plan -> execute

But if the user goes into debug mode, they can serialize the execution plan into JSON/YAML etc. This way they can inspect exactly what's going on, copy it into unit tests, or compare to equivalent KCL programs that just have different whitespace or comments.

So, there's be two representations of EPs:

- In-memory vec of arrays (tightly coupled to Rust, exported as a Rust library and used in KCMA and Engine)
- Serialized format (either JSON or BSON or really anything Serde can handle)

Regarding math equations, we can just store a tree of math operations, where operands are either literals or registers.

**Comment by Irev-Dev** [comment]
Yup perfect, DSL didn't quite seem worth the investment to me, and yeah JSON already handles nesting fine so using that for math works well.

As for as debug mode goes, JSON/YAML ofc is perfect for being able to paste into GH issue or paste into our tests, but we could also put dev-tools in the modelling app that give a richer experience, for example linking to docs for each of the endpoints (or better embedding them).

Actually I have another request, could we put source ranges (start end) in the execution plan? They can be removed before we give them to the user since they are not important for running the execution plan, but with the previous point of having a good debug experience in the app, we could add an `execution plan explorer` to match the `AST explorer`

https://github.com/KittyCAD/modeling-app/assets/29681384/e8811d2f-6183-4acb-870b-2e527794a88d

**Comment by adamchalmers** [comment]
Sure, but the source ranges should be optional. They make sense for KCMA but not for unit tests.

**Comment by Irev-Dev** [comment]
Upon reflection, I realised the source ranges are much much more important than just a dev tools thing.

So with the current tree walk execution when a node that will create an engine artifact is executed (stdlib callExpression effectively) because we have the source range of the node right there, we can link the id of the artifact to the source range of the node, and the mapping is a must.

If we separate the tree-walk from the engine calls than we need a way to bring those source ranges through. They can still be optional params as far as the EP struct goes, but they are not optional as far as KCMA is concerned.

Unless there is another way to link engine artifacts back to source-ranges. Perhaps when we create each item in the EP, that's when we create the `cmd_id` that will be used for the engine call that way we can link the two before the execution has taken place. That might work but now I'm wondering if they will always be 1:1 after we start adding optimizations to the EP?

**Comment by adamchalmers** [comment]
@Irev-Dev Damnit, I remember we talked about this (linking source ranges/command IDs to EPs) on a call but I can't remember what we decided.

**Comment by Irev-Dev** [comment]
Haha, I'm not sure I remember either.

I've been thinking about this for the last 10 minutes and don't seem to be able to retrace our reasoning from memory to be confident what the answer was. 

I'll keep it on the back burner, but happy to huddle too.

**Comment by adamchalmers** [comment]
I realized the initial proposal above misses a big question: how does an EP store structs? Can a register store an entire struct? If so, how do we represent it in Rust?

1. Store BSON binary in each register, serialize values when writing to register and deserialize them when reading from.
2. Store Box<dyn Serialize + Deserialize + Debug> in each register
3. Decompose each struct into its separate fields, store each field in its own register as an enum with variants for ints, floats, strings etc. When updating a field, you only have to update one value. When writing structs to/reading structs from memory, just de/compose them into fields.

Option 2 is tricky due to Rust's dynamic dispatch shenanigans. Like option 1 it would require runtime checks that the value in memory is the type you expect. So, I'd prefer option 1 or 3.

**Comment by jessfraz** [comment]
just noting when this is done we can close https://github.com/KittyCAD/modeling-app/issues/914
