### ISSUE TITLE
no kcl errors are being thrown anymore in the app

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#994]
<img width="1115" alt="Screenshot 2023-11-03 at 2 43 25 PM" src="https://github.com/KittyCAD/modeling-app/assets/1445228/9b7fbde2-95ed-4635-8523-3b38058a6fbe">

again a situation where playwight could have likely caught

**Comment by jessfraz** [comment]
this is broken in the current release as well

**Comment by adamchalmers** [comment]
<img width="585" alt="kcl bug" src="https://github.com/KittyCAD/modeling-app/assets/5407457/9ff88750-dfde-4fd1-a79a-ae66c12b449f">

This program has two bugs (there's a # instead of a // for the initial comment, and the extrude command only has 1 arg instead of 2). Neither bug shows up in the KCL Errors panel, and neither shows up as a CodeMirror diagnostic either.
